// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_app/test/unit/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_app/core/api/agri_pulse_service.dart' as _i6;
import 'package:flutter_app/features/auth/domain/auth_repository.dart' as _i3;
import 'package:flutter_app/features/auth/domain/entities/farmer.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFarmer_0 extends _i1.SmartFake implements _i2.Farmer {
  _FakeFarmer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Future<String> sendOtp(String? phoneNumber) => (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [phoneNumber],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #sendOtp,
            [phoneNumber],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #sendOtp,
            [phoneNumber],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.Farmer> verifyOtp({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [],
          {
            #verificationId: verificationId,
            #smsCode: smsCode,
          },
        ),
        returnValue: _i4.Future<_i2.Farmer>.value(_FakeFarmer_0(
          this,
          Invocation.method(
            #verifyOtp,
            [],
            {
              #verificationId: verificationId,
              #smsCode: smsCode,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Farmer>.value(_FakeFarmer_0(
          this,
          Invocation.method(
            #verifyOtp,
            [],
            {
              #verificationId: verificationId,
              #smsCode: smsCode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Farmer>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Farmer?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Farmer?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.Farmer?>.value(),
      ) as _i4.Future<_i2.Farmer?>);

  @override
  _i4.Future<_i2.Farmer> skipLogin() => (super.noSuchMethod(
        Invocation.method(
          #skipLogin,
          [],
        ),
        returnValue: _i4.Future<_i2.Farmer>.value(_FakeFarmer_0(
          this,
          Invocation.method(
            #skipLogin,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Farmer>.value(_FakeFarmer_0(
          this,
          Invocation.method(
            #skipLogin,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Farmer>);
}

/// A class which mocks [AgriPulseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgriPulseService extends _i1.Mock implements _i6.AgriPulseService {
  @override
  _i4.Future<Map<String, dynamic>> analyzeCrop(
    _i7.XFile? imageFile,
    String? farmerId,
    String? voiceTranscription, {
    Map<String, dynamic>? weatherContext,
    String? languageCode,
    String? irrigationStage,
    String? soilMoisture,
    String? weatherEvent,
    String? spreadPattern,
    String? lastTreatment,
    String? dosage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeCrop,
          [
            imageFile,
            farmerId,
            voiceTranscription,
          ],
          {
            #weatherContext: weatherContext,
            #languageCode: languageCode,
            #irrigationStage: irrigationStage,
            #soilMoisture: soilMoisture,
            #weatherEvent: weatherEvent,
            #spreadPattern: spreadPattern,
            #lastTreatment: lastTreatment,
            #dosage: dosage,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getForecast(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getCurrentWeather(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [
            lat,
            lon,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<int>> synthesizeSpeech(
    String? text,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #synthesizeSpeech,
          [
            text,
            languageCode,
          ],
        ),
        returnValue: _i4.Future<List<int>>.value(<int>[]),
        returnValueForMissingStub: _i4.Future<List<int>>.value(<int>[]),
      ) as _i4.Future<List<int>>);

  @override
  _i4.Future<Map<String, dynamic>> predictYield({
    required String? farmerId,
    required String? cropName,
    required double? fieldArea,
    required String? plantedDate,
    required String? soilType,
    required Map<String, dynamic>? weatherForecast,
    String? expectedHarvestDate,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictYield,
          [],
          {
            #farmerId: farmerId,
            #cropName: cropName,
            #fieldArea: fieldArea,
            #plantedDate: plantedDate,
            #soilType: soilType,
            #weatherForecast: weatherForecast,
            #expectedHarvestDate: expectedHarvestDate,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> translateText(
    String? text,
    String? targetLanguage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #translateText,
          [
            text,
            targetLanguage,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #translateText,
            [
              text,
              targetLanguage,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #translateText,
            [
              text,
              targetLanguage,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> refineDiagnosis({
    required String? farmerId,
    required Map<String, dynamic>? originalDiagnosis,
    required String? feedback,
    required Map<String, dynamic>? contextOverrides,
    List<Map<String, dynamic>>? interactionHistory,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refineDiagnosis,
          [],
          {
            #farmerId: farmerId,
            #originalDiagnosis: originalDiagnosis,
            #feedback: feedback,
            #contextOverrides: contextOverrides,
            #interactionHistory: interactionHistory,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
