const Map<String, String> hindiTranslations = {
  'yield_prediction': 'उपज भविष्यवाणी',
  'predict_harvest': 'अपनी फसल का अनुमान लगाएं',
  'enter_details': 'एआई-आधारित उपज अनुमान के लिए अपने खेत का विवरण दर्ज करें।',
  'crop_details': 'फसल का विवरण',
  'field_name': 'खेत का नाम',
  'crop_name': 'फसल का नाम',
  'field_area': 'खेत का क्षेत्रफल (एकड़)',
  'environment': 'पर्यावरण',
  'soil_type': 'मिट्टी का प्रकार',
  'planted_date': 'रोपण की तारीख',
  'get_prediction': 'भविष्यवाणी प्राप्त करें',
  'gemini_hint': 'जेमिनी 3.0 प्रो वास्तविक समय के मौसम के पूर्वानुमान के साथ इन कारकों का विश्लेषण करेगा।',
  'yield_forecast': 'उपज का अनुमान',
  'confidence': 'आत्मविश्वास',
  'core_factors': 'मुख्य कारक',
  'ai_strategy': 'एआई रणनीति',
  'onion': 'प्याज',
  'tomato': 'टमाटर',
  'potato': 'आलू',
  'rice': 'चावल',
  'wheat': 'गेहूं',
  'maize': 'मक्का',
  'cotton': 'कपास',
  'sugarcane': 'गन्ना',
  'clay_loam': 'दोमट मिट्टी',
  'sandy_soil': 'बलुई मिट्टी',
  'sandy_loam': 'बलुई दोमट मिट्टी',
  'red_loamy': 'लाल दोमट मिट्टी',
  'black_cotton': 'काली कपास मिट्टी',
  'silt_loam': 'गाद दोमट मिट्टी',
  'peat': 'पीट',
  'chalky': 'चाकयुक्त',
  'black_soil': 'काली मिट्टी',
  'red_soil': 'लाल मिट्टी',
  'acres': 'एकड़',
  'select_language': 'भाषा चुनें',
  'language': 'भाषा',
  'yield_outlook': '7-दिवसीय उपज दृष्टिकोण',
  'good_potential': 'अच्छी क्षमता',
  'climatic_stress': ' जलवायु तनाव',
  'field_parameters': 'खेत के पैरामीटर',
  'system_health': 'सिस्टम स्वास्थ्य',
  'active_feed': 'सक्रिय फीड:',
  'api_stable': 'मौसम_एपीआई_स्थिर',
  'estimated_yield': 'अनुमानित उपज',
  'low_reliability': 'कम विश्वसनीयता',
  'medium_reliability': 'मध्यम विश्वसनीयता',
  'high_reliability': 'उच्च विश्वसनीयता',
  'yield_trajectory': '7-दिवसीय उपज प्रक्षेपवक्र',
  'contextual_insights': 'प्रासंगिक अंतर्दृष्टि',
  'temperature': 'तापमान',
  'soil_moisture': 'मिट्टी की नमी',
  'disease_risk': 'रोग का जोखिम',
  'sunlight': 'सूर्य का प्रकाश',
  'optimal': 'इष्टतम',
  'monitor': 'निगरानी',
  'warning': 'चेतावनी',
  'good': 'अच्छा',
  'diffuse': 'विसरित',
  'expected_harvest_date': 'अपेक्षित फसल की तारीख',
  'run_prediction': 'भविष्यवाणी चलाएँ',
  'harvest_window_warning': 'उत्पत्ति की तिथि 14 दिनों की मौसम की सीमा से परे है। AI मौसમી जलवायु के औसत का उपयोग करेगा।',
  'financial_outlook': 'वित्तीय दृष्टिकोण',
  'projected_revenue': 'अनुमानित राजस्व',
  'estimated_cost': 'अनुमानित लागत',
  'net_profit': 'शुद्ध लाभ',
  'financial_disclaimer': '* {cropName} के लिए वर्तमान बाजार औसत पर आधारित अनुमान। वास्तविक रिटर्न भिन्न हो सकते हैं।',
  'hello': 'नमस्ते',
  'smart_tools': 'स्मार्ट टूल्स',
  'crop_doctor': 'फसल डॉक्टर',
  'crop_doctor_desc': 'AI पौधों का निदान',
  'yield_est': 'उपज अनुमान',
  'yield_est_desc': 'मौसम से उपज की भविष्यवाणी',
  'market': 'बाज़ार',
  'market_desc': 'लाइव फसल कीमतें',
  'ask_expert': 'विशेषज्ञ से पूछें',
  'ask_expert_desc': '24/7 कृषि मार्गदर्शन', 
  'rice_field': 'धान का खेत',
  'wheat_field': 'गेहूं का खेत',
  'corn_field': 'मक्का का खेत',
  'onion_field': 'प्याज का खेत',
  'tomato_field': 'टमाटर का खेत',
  'cotton_field': 'कपास का खेत',
  'sugarcane_field': 'गन्ने का खेत',
  'vegetable_patch': 'सब्जी बगीचा',
  'custom_input': 'कस्टम',
  'acreage_small': '< 1 एकड़',
  'acreage_medium': '1-2 एकड़',
  'acreage_large': '2-5 एकड़',
  'acreage_very_large': '5-10 एकड़',
  'acreage_estate': '> 10 एकड़',
  'login_tagline': 'आपका बुद्धिमान खेती साथी',
  'login_title': 'किसान लॉगिन',
  'login_otp_title': 'सत्यापन कोड दर्ज करें',
  'login_phone_label': 'फ़ोन नंबर',
  'login_phone_hint': '98765 43210',
  'login_send_otp': 'OTP भेजें',
  'login_otp_sent_to': 'भेजा गया',
  'login_verify': 'सत्यापित करें और लॉगिन करें',
  'login_change_number': 'नंबर बदलें',
  'login_powered_by': 'Gemini 3.0 द्वारा संचालित',
  'upload_crop_image': 'फसल की छवि अपलोड करें',
  'take_photo_instruction': 'प्रभावित क्षेत्र की स्पष्ट फोटो लें',
  'upload_image': 'छवि अपलोड करें',
  'supports_formats': 'समर्थन: JPG, PNG',
  'camera': 'कैमरा',
  'gallery': 'गेलरी',
  'analyze_crop': 'फसल का विश्लेषण करें',
  'analyzing': 'विश्लेषण जारी है...',
  'identifying_diseases': 'संभावित रोगों की पहचान की जा रही है',
  'diagnosis_results': 'निदान परिणाम',
  'diagnosis_placeholder': 'विस्तृत रिपोर्ट देखने के लिए छवि अपलोड करें और विश्लेषण पर क्लिक करें।',
  'detected_issue': 'पता चला मुद्दा',
  'healthy_plant': 'स्वस्थ पौधा',
  'recommended_treatment': 'अनुशंसित उपचार',
  'generate_report': 'रिपोर्ट तैयार करें',
  'listen_advice': 'सलाह सुनें',
  'playing_advice': 'सलाह चल रही है...',
  'getting_audio': 'ऑडियो प्राप्त कर रहा है...',
  'describe_issue_hint': 'समस्या का वर्णन करें',
  'climate_aware_forecasting': 'जलवायु-जागरूक पूर्वानुमान',
  'ai_engine_reasoning': 'एक बार जब आप अपने खेत का विवरण प्रदान करते हैं, तो हमारा एआई इंजन जेमिनी 3.0 प्रो का उपयोग करके इन पर बहु-कारक तर्क करता है:',
  'reasoning_factor_1': 'स्थानीय 7-दिवसीय मौसम पूर्वानुमान',
  'reasoning_factor_2': 'फसल-विशिष्ट विकास चक्र',
  'reasoning_factor_3': 'मिट्टी उत्पादकता मॉडल',
  'reasoning_factor_4': 'क्षेत्रीय इतिहास',
  'challenge_diagnosis': 'निदान को चुनौती दें',
  'ai_reasoning': 'एआई तर्क',
  'soil_condition': 'मिट्टी की स्थिति',
  'weather_condition': 'मौसम की स्थिति',
  'missed_info_hint': 'मैंने क्या याद किया? (उदाहरण, "पत्तियाँ चिपचिपी हैं")',
  'provide_feedback_error': 'कृपया सुधारने के लिए संदर्भ या प्रतिक्रिया दें।',
  'soil_normal': 'सामान्य',
  'soil_dry': 'सूखी/रेतीली',
  'soil_wet': 'गीली/चिकनी',
  'soil_log': 'जल भराव',
  'weather_sunny': 'धूप',
  'weather_cloudy': 'बादल छाए रहेंगे',
  'weather_rain': 'भारी बारिश',
  'weather_windy': 'हवादार',
  'refining': 'परिष्कृत कर रहा है...',
  'ask_second_opinion': 'दूसरी राय पूछें',
  'select_harvest_date': 'कृपया पहले अनुमानित फसल तिथि चुनें।',
  'prediction_failed': 'भविष्यवाणी विफल रही',
  'retry': 'पुनः प्रयास करें',
  'soil_and_environment': 'मिट्टी और पर्यावरण',
  'help_gemini_understand': 'जेमिनी को अपनी भूमि समझने में मदद करें।',
  'select_soil_texture': 'मिट्टी की बनावट चुनें',
  'irrigation_method': 'सिंचाई की विधि',
  'how_do_you_water': 'आप अपनी फसलों को पानी कैसे देते हैं?',
  'welcome_agripulse': 'AgriPulse में आपका स्वागत है',
  'setup_first_plot': 'व्यक्तिगत एआई सलाह प्राप्त करने के लिए अपना पहला फार्म प्लॉट सेट करें।',
  'plot_name': 'प्लॉट का नाम',
  'approx_acreage': 'अनुमानित क्षेत्रफल',
  'continue': 'जारी रखें',
  'finish_setup': 'सेटअप समाप्त करें',
  'my_first_plot': 'मेरा पहला प्लॉट',
  'register_new_plot': 'नया प्लॉट पंजीकृत करें',
  'plot_info': 'प्लॉट की जानकारी',
  'ground_advice_hint': 'प्लॉट विवरण प्रदान करके AgriPulse को अपनी सलाह को बेहतर बनाने में मदद करें।',
  'submit_registration': 'पंजीकरण जमा करें',
  'drip': 'ड्रिप',
  'sprinkler': 'स्प्रिंकलर',
  'manual_bucket': 'मैनुअल / बाल्टी',
  'flood': 'बाढ़ सिंचाई',
  'rain_fed': 'वर्षा आधारित',
  'clay_loam_desc': 'बेहतरीन जल प्रतिधारण, उच्च पोषक तत्व।',
  'sandy_soil_desc': 'तेजी से जल निकासी, बार-बार सिंचाई की आवश्यकता।',
  'red_loamy_desc': 'संतुलित जल निकासी, अधिकांश फसलों के लिए अच्छा।',
  'black_cotton_desc': 'उच्च नमी क्षमता, कपास/प्याज के लिए आदर्श।',
  'recent_activity': 'हाल की गतिविधि',
  'see_all': 'सभी देखें',
  'error_loading_activity': 'गतिविधि लोड करने में त्रुटि',
  'move_to_plot': 'प्लॉट में ले जाएं',
  'no_activity_yet': 'अभी तक कोई गतिविधि नहीं',
  'start_scan_prediction_hint': 'इतिहास देखने के लिए फसल स्कैन या उपज भविष्यवाणी शुरू करें',
  'move_record_to_plot': 'रिकॉर्ड को प्लॉट में ले जाएं',
  'select_destination_plot': 'इस गतिविधि के लिए गंतव्य प्लॉट चुनें।',
  'moved_successfully': 'सफलतापूर्वक स्थानांतरित किया गया!',
  'today': 'आज',
  'yesterday': 'कल',
  'm_ago': 'मि पहले',
  'h_ago': 'घं पहले',
  // Field Selector
  'select_plot': 'प्लॉट चुनें',
  'switch_plot_hint': 'प्लॉट संदर्भ बदलने के लिए स्पर्श करें',
  'select_farming_plot': 'खेती के प्लॉट का चयन करें',
  'plot_environment_hint': 'AgriPulse सभी एआई सलाह को चयनित प्लॉट वातावरण के अनुसार देगा।',
  'main_plot_north': 'मुख्य प्लॉट (उत्तर)',
  'unassigned_legacy_data': 'सामान्य पूछताछ',
  'unknown_crop': 'अज्ञात फसल',
  'mixed_soil': 'मिश्रित मिट्टी',
  'activity_log': 'गतिविधि लॉग',
  'search_history_hint': 'इतिहास खोजें...',
  'detailed_report': 'विस्तृत रिपोर्ट',
  'select_record_detail': 'विवरण देखने के लिए एक रिकॉर्ड चुनें',
  'detailed_data_unavailable': 'इस ऐतिहासिक रिकॉर्ड के लिए विस्तृत डेटा अनुपलब्ध है।',
  'run_new_prediction_hint': 'पूर्ण विवरण देखने के लिए कृपया एक नई भविष्यवाणी चलाएं।',
  'health_status': 'स्वास्थ्य स्थिति',
  'diagnosis_analysis': 'निदान विश्लेषण',
  'severity_score': 'गंभीरता स्कोर',
  'severity_high': 'उच्च',
  'severity_medium': 'मध्यम',
  'severity_low': 'कम',
  'environmental_status': 'पर्यावरण स्थिति',
  'confidence_metrics': 'आत्मविश्वास मेट्रिक्स',
  'ai_recommendation': 'एआई सिफारिश',
  'soil_correction': 'मिट्टी सुधार',
  'model_precision': 'मॉडल परिशुद्धता',
  'verified_ai': 'AgriPulse AI द्वारा सत्यापित',
  'findings': 'निदान निष्कर्ष',
  'confidence_score_cap': 'आत्मविश्वास स्कोर',
  'qtl_acre': 'क्विंटल/एकड़',
  'clear_history': 'इतिहास मिटाएं',
  'clear_history_confirm': 'क्या आप वाकई सारा इतिहास मिटाना चाहते हैं?',
  'delete_plot': 'खेत हटाएं',
  'delete_plot_confirm': 'क्या आप वाकई इस खेत को हटाना चाहते हैं?',
  'clear': 'मिटाएं',
  'cancel': 'रद्द करें',
  'market_insights': 'बाज़ार अंतर्दृष्टि',
  'treatment_plan': 'उपचार योजना',
  'humidity': 'आर्द्रता',
  'confidence_level': 'आत्मविश्वास स्तर',
  'jan': 'जनवरी',
  'feb': 'फरवरी',
  'mar': 'मार्च',
  'apr': 'अप्रैल',
  'may': 'मई',
  'jun': 'जून',
  'jul': 'जुलाई',
  'aug': 'अगस्त',
  'sep': 'सितंबर',
  'oct': 'अक्टूबर',
  'nov': 'नवंबर',
  'dec': 'दिसंबर',
  'analysis_failed_connection': 'विश्लेषण विफल रहा। कनेक्शन त्रुटि।',
  'refinement_failed': 'परिष्करण विफल रहा',
  'audio_empty_error': 'सर्वर से खाली ऑडियो प्राप्त हुआ।',
  'audio_play_failed': 'सलाह चलाने में विफल',
  'unknown_issue': 'अज्ञात मुद्दा',
  'consult_expert': 'किसी विशेषज्ञ से सलाह लें।',
  'no_advice_available': 'कोई सलाह उपलब्ध नहीं है।',
  'diagnosis_prefix': 'निदान',
  'recommendation_prefix': 'सिफारिश',
  'scan_in': 'स्कैन:',
  'irrigation_stage': 'सिंचाई चरण',
  'weather_events': 'मौसम की घटनाएं',
  'spread_pattern': 'प्रसार पैटर्न',
  'intervention_log': 'उपचार लॉग',
  'establishment': 'स्थापना',
  'sprouting': 'अंकुरण',
  'leaf_dev': 'पत्ता विकास',
  'bulb_init': 'कंद दीक्षा',
  'bulb_dev': 'कंद विकास',
  'bone_dry': 'सूखा',
  'moist': 'नम',
  'waterlogged': 'जलभराव',
  'frost': 'ठंड',
  'heavy_rain': 'भारी बारिश',
  'drizzle': 'बूंदाबांदी',
  'wind': 'हवा',
  'too_hot': 'बहुत गर्म',
  'isolated': 'अलग',
  'localized': 'स्थानीय',
  'field_wide': 'पूरे खेत में',
  'last_treatment': 'पिछला उपचार',
  'dosage': 'खुराक',
  'fert_organic': 'जैविक',
  'fert_npk': 'एनपीके',
  'fungicide': 'कवकनाशी',
  'insecticide': 'कीटनाशक',
  'low': 'कम',
  'medium': 'मध्यम',
  'high': 'उच्च',
  'workspace_context': 'खेत का संदर्भ',
  'leaf_texture': 'पत्ती की बनावट',
  'texture_brittle': 'भुरभुरा/कुरकुरा',
  'texture_slimy': 'लसदार/कोमल',
  'texture_rubbery': 'रबड़ जैसा/सख्त',
  'odor_presence': 'गंध की उपस्थिति',
  'odor_foul': 'दुर्गंध/सड़न',
  'odor_none': 'कोई गंध नहीं',
  'speed_of_spread': 'फैलाव की गति',
  'spread_overnight': 'रातों-रात दिखाई दिया',
  'spread_slow': 'धीरे-धीरे बढ़ रहा है (2+ सप्ताह)',
  // Recursive Insight
  'role_user': 'आप',
  'role_ai': 'AgriPulse AI',
  'analysis_complete': 'विश्लेषण पूर्ण',
  'default_ai_response': 'आपकी प्रतिक्रिया के आधार पर अद्यतन निदान।',
  'treatment_adjustment_label': 'सुधार',
  'sidebar_waiting_hint': 'विश्लेषण की प्रतीक्षा की जा रही है... दिखाई देने पर एआई निदान को परिष्कृत करने के लिए इस अनुभाग का उपयोग करें।',
  'view_report': 'रिपोर्ट देखें',
  'initial_request': 'शुरुआती अनुरोध',
  'initial_diagnosis': 'शुरुआती निदान',
  'refined_diagnosis': 'परिष्कृत निदान',
  'refinement_reasoning': 'परिष्करण तर्क',
  'refinement_feedback': 'परिष्करण प्रतिक्रिया',
  'ai_findings': 'एआई निष्कर्ष',
  'adjusted_treatment_plan': 'समायोजित उपचार योजना',
  'view_standard_treatment': 'मानक उपचार देखें',
  'view_adjusted_plan': 'समायोजित योजना देखें',
  'delete': 'हटाएं',
  'delete_record_confirm': 'क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?',
  'record_deleted': 'रिकॉर्ड हटा दिया गया',
  'prediction': 'अनुमान',
  'forecast': 'पूर्वानुमान',
};
