const Map<String, String> teluguTranslations = {
  'yield_prediction': 'దిగుబడి అంచనా',
  'predict_harvest': 'మీ పంటను అంచనా వేయండి',
  'enter_details': 'AI-ఆధారిత దిగుబడి అంచనా కోసం మీ పొలం వివరాలను నమోదు చేయండి.',
  'crop_details': 'పంట వివరాలు',
  'field_name': 'పొలం పేరు',
  'crop_name': 'పంట పేరు',
  'field_area': 'పొలం విస్తీర్ణం (ఎకరాలు)',
  'environment': 'పర్యావరణం',
  'soil_type': 'నేల రకం',
  'planted_date': 'నాటిన తేదీ',
  'get_prediction': 'అంచనా పొందండి',
  'gemini_hint': 'జెమిని 3.0 ప్రో నిజ-సమయ వాతావరణ అంచనాలతో ఈ కారకాలను విశ్లేషిస్తుంది.',
  'yield_forecast': 'దిగుబడి అంచనా',
  'confidence': 'విశ్వాసం',
  'core_factors': 'ముఖ్య కారకాలు',
  'ai_strategy': 'AI వ్యూహం',
  'onion': 'ఉల్లిపాయ',
  'tomato': 'టమాటా',
  'potato': 'బంగాళదుంప',
  'rice': 'వరి',
  'wheat': 'గోధుమ',
  'maize': 'మొక్కజొన్న',
  'cotton': 'ప్రత్తి',
  'sugarcane': 'చెరకు',
  'clay_loam': 'బంకమట్టి నేల',
  'sandy_soil': 'ఇసుక నేల',
  'sandy_loam': 'ఇసుక లోమ్ నేల',
  'red_loamy': 'ఎరుపు నేల',
  'black_cotton': 'నల్ల పత్తి నేల',
  'silt_loam': 'సిల్ట్ లోమ్ నేల',
  'peat': 'పీట్ నేల',
  'chalky': 'సుద్ద నేల',
  'black_soil': 'నల్ల రేగడి నేల',
  'red_soil': 'ఎర్ర నేల',
  'acres': 'ఎకరాలు',
  'select_language': 'భాషను ఎంచుకోండి',
  'language': 'భాష',
  'yield_outlook': '7-రోజుల దిగుబడి దృక్పథం',
  'good_potential': 'మంచి దిగుబడి సామర్థ్యం',
  'climatic_stress': 'వాతావరణ ఒత్తిడి',
  'field_parameters': 'పొలం పారామీటర్లు',
  'system_health': 'సిస్టమ్ ఆరోగ్యం',
  'active_feed': 'యాక్టివ్ ఫీడ్:',
  'api_stable': 'వాతావరణ_API_స్థిరంగా ఉంది',
  'estimated_yield': 'అంచనా వేసిన దిగుబడి',
  'low_reliability': 'తక్కువ విశ్వసనీయత',
  'medium_reliability': 'మధ్యస్థ విశ్వసనీయత',
  'high_reliability': 'అధిక విశ్వసనీయత',
  'yield_trajectory': '7-రోజుల దిగుబడి పథం',
  'contextual_insights': 'సందర్భోచిత అంతర్దృష్టులు',
  'temperature': 'ఉష్ణోగ్రత',
  'soil_moisture': 'నేల తేమ',
  'disease_risk': 'వ్యాధి ప్రమాదం',
  'sunlight': 'సూర్యరశ్మి',
  'optimal': 'అత్యుత్తమ',
  'monitor': 'పర్యవేక్షించు',
  'warning': 'హెచ్చరిక',
  'good': 'మంచిది',
  'diffuse': 'వ్యాపించిన',
  'expected_harvest_date': 'నిరీక్షిత కోత తేదీ',
  'run_prediction': 'భవిష్యత్తును అంచనా వేయండి',
  'harvest_window_warning': 'గమనిక: కోత తేదీ 14 రోజుల వాతావరణ పరిధికి మించి ఉంది. AI కాలిక అవసరాలను బట్టి అంచనా వేస్తుంది.',
  'financial_outlook': 'ఆర్థిక దృక్పథం',
  'projected_revenue': 'అంచనా వేసిన ఆదాయం',
  'estimated_cost': 'అంచనా వేసిన ఖర్చు',
  'net_profit': 'నికర లాభం',
  'financial_disclaimer': '* {cropName} ప్రస్తుత మార్కెట్ సగటు ఆధారిత అంచనాలు. అసలు రాబడి మారవచ్చు.',
  'hello': 'నమస్కారం',
  'smart_tools': 'స్మార్ట్ సాధనాలు',
  'crop_doctor': 'పంట డాక్టర్',
  'crop_doctor_desc': 'AI మొక్కల రోగ నిర్దారణ',
  'yield_est': 'దిగుబడి అంచనా',
  'yield_est_desc': 'వాతావరణ పూర్వానుమానం',
  'market': 'మార్కెట్',
  'market_desc': 'లైవ్ ధరలు & ట్రెండ్‌లు',
  'ask_expert': 'నిపుణుడిని అడగండి',
  'ask_expert_desc': '24/7 వ్యవసాయ మార్గదర్శనం',
  'rice_field': 'వరి పొలం',
  'wheat_field': 'గోధుమ పొలం',
  'corn_field': 'మొక్కజొన్న పొలం',
  'onion_field': 'ఉల్లిపాయ పొలం',
  'tomato_field': 'టమోటా పొలం',
  'cotton_field': 'పత్తి పొలం',
  'sugarcane_field': 'చెరకు పొలం',
  'vegetable_patch': 'కూరగాయల తోట',
  'custom_input': 'కస్టమ్',
  'acreage_small': '< 1 ఎకరం',
  'acreage_medium': '1-2 ఎకరాలు',
  'acreage_large': '2-5 ఎకరాలు',
  'acreage_very_large': '5-10 ఎకరాలు',
  'acreage_estate': '> 10 ఎకరాలు',
  'login_tagline': 'మీ తెలివైన వ్యవసాయ సహచరుడు',
  'login_title': 'రైతు లాగిన్',
  'login_otp_title': 'ధృవీకరణ కోడ్‌ను నమోదు చేయండి',
  'login_phone_label': 'ఫోన్ నంబర్',
  'login_phone_hint': '98765 43210',
  'login_send_otp': 'OTP పంపండి',
  'login_otp_sent_to': 'పంపబడింది',
  'login_verify': 'ధృవీకరించండి & లాగిన్ చేయండి',
  'login_change_number': 'నంబర్ మార్చండి',
  'login_powered_by': 'Gemini 3.0 ద్వారా అందించబడింది',
  'upload_crop_image': 'పంట చిత్రాన్ని అప్‌లోడ్ చేయండి',
  'take_photo_instruction': 'ప్రభావిత ప్రాంతం యొక్క స్పష్టమైన ఫోటో తీయండి',
  'upload_image': 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
  'supports_formats': 'మద్దతు ఇస్తుంది: JPG, PNG',
  'camera': 'కెమెరా',
  'gallery': 'గ్యాలరీ',
  'analyze_crop': 'పంటను విశ్లేషించండి',
  'analyzing': 'విశ్లేషిస్తోంది...',
  'identifying_diseases': 'వ్యాధులను గుర్తిస్తోంది',
  'diagnosis_results': 'ఫలితాలు',
  'diagnosis_placeholder': 'చిత్రాన్ని అప్‌లోడ్ చేసి విశ్లేషించండి',
  'detected_issue': 'గుర్తించిన సమస్య',
  'healthy_plant': 'ఆరోగ్యకరమైన మొక్క',
  'recommended_treatment': 'సిఫార్సు చేసిన చికిత్స',
  'generate_report': 'నివేదికను రూపొందించండి',
  'listen_advice': 'సలహా వినండి',
  'playing_advice': 'సలహా వినిపిస్తోంది...',
  'getting_audio': 'ఆడియో వస్తోంది...',
  'describe_issue_hint': 'సమస్యను వివరించండి',
  'climate_aware_forecasting': 'వాతావరణ-అవగాహన అంచనా',
  'ai_engine_reasoning': 'మీరు మీ పొలం వివరాలను అందించిన తర్వాత, మా AI ఇంజిన్ జెమిని 3.0 ప్రో వీటిపై బహుళ-కారక విశ్లేషణ చేస్తుంది:',
  'reasoning_factor_1': 'స్థానిక 7-రోజుల వాతావరణ సూచనలు',
  'reasoning_factor_2': 'పంట-నిర్దిష్ట పెరుగుదల చక్రాలు',
  'reasoning_factor_3': 'నేల ఉత్పాదకత నమూనాలు',
  'reasoning_factor_4': 'ప్రాంతీయ చరిత్ర',
  'challenge_diagnosis': 'రోగనిర్ధారణను సవాలు చేయండి',
  'ai_reasoning': 'AI రీజనింగ్',
  'soil_condition': 'నేల పరిస్థితి',
  'weather_condition': 'వాతావరణ స్థితి',
  'missed_info_hint': 'నేను ఏమి మిస్ అయ్యాను?',
  'provide_feedback_error': 'దయచేసి ఫీడ్‌బ్యాక్ ఇవ్వండి.',
  'soil_normal': 'సాధారణ',
  'soil_dry': 'పొడి/ఇసుక',
  'soil_wet': 'తడి/బంకమట్టి',
  'soil_log': 'నీరు నిలిచిపోయింది',
  'weather_sunny': 'ఎండ',
  'weather_cloudy': 'మబ్బు',
  'weather_rain': 'భారీ వర్షం',
  'weather_windy': 'గాలి',
  'refining': 'శుద్ధి చేస్తోంది...',
  'ask_second_opinion': 'రెండవ అభిప్రాయం అడగండి',
  'select_harvest_date': 'దయచేసి ముందుగా అంచనా వేసిన కోత తేదీని ఎంచుకోండి.',
  'prediction_failed': 'అంచనా విఫలమైంది',
  'retry': 'మళ్ళీ ప్రయత్నించండి',
  'soil_and_environment': 'నేల మరియు పర్యావరణం',
  'help_gemini_understand': 'మీ భూమిని అర్థం చేసుకోవడానికి జెమిని సహాయపడండి.',
  'select_soil_texture': 'నేల ఆకృతిని ఎంచుకోండి',
  'irrigation_method': 'నీటి పారుదల పద్ధతి',
  'how_do_you_water': 'మీ పంటలకు మీరు ఎలా నీరు పోస్తారు?',
  'welcome_agripulse': 'AgriPulseకి స్వాగతం',
  'setup_first_plot': 'వ్యక్తిగతీకరించిన AI సలహాను పొందడానికి మీ మొదటి ఫామ్ ప్లాట్‌ను సెటప్ చేయండి.',
  'plot_name': 'ప్లాట్ పేరు',
  'approx_acreage': 'సుమారు ఎకరాలు',
  'continue': 'కొనసాగించండి',
  'finish_setup': 'సెటప్ పూర్తి చేయండి',
  'my_first_plot': 'నా మొదటి ప్లాట్',
  'register_new_plot': 'కొత్త ప్లాట్‌ను నమోదు చేయండి',
  'plot_info': 'ప్లాట్ సమాచారం',
  'ground_advice_hint': 'ప్లాట్ వివరాలను అందించడం ద్వారా AgriPulse తన సలహాలను మెరుగుపరచడానికి సహాయపడండి.',
  'submit_registration': 'రిజిస్ట్రేషన్ సమర్పించండి',
  'drip': 'బిందు సేద్యం',
  'sprinkler': 'స్ప్రింక్లర్',
  'manual_bucket': 'మాన్యువల్ / బకెట్',
  'flood': 'వరద నీటి పారుదల',
  'rain_fed': 'వర్షాధారం',
  'clay_loam_desc': 'అద్భుతమైన నీటిని నిలుపుకునే సామర్థ్యం, అధిక పోషకాలు.',
  'sandy_soil_desc': 'వేగవంతమైన డ్రైనేజీ, తరచుగా నీటి పారుదల అవసరం.',
  'red_loamy_desc': 'సమతుల్య డ్రైనేజీ, చాలా పంటలకు అనువైనది.',
  'black_cotton_desc': 'అధిక తేమ సామర్థ్యం, పత్తి/ఉల్లి పంటలకు అనువైనది.',
  'recent_activity': 'ఇటీవలి కార్యాచరణ',
  'see_all': 'అన్నీ చూడండి',
  'error_loading_activity': 'కార్యాచరణను లోడ్ చేయడంలో లోపం',
  'move_to_plot': 'ప్లాట్‌కు తరలించండి',
  'no_activity_yet': 'ఇంకా ఎటువంటి కార్యాచరణ లేదు',
  'start_scan_prediction_hint': 'చరిత్రను చూడటానికి పంట స్కాన్ లేదా దిగుబడి అంచనాను ప్రారంభించండి',
  'move_record_to_plot': 'రికార్డును ప్లాట్‌కు తరలించండి',
  'select_destination_plot': 'ఈ కార్యాచరణ కోసం గమ్యస్థాన ప్లాట్‌ను ఎంచుకోండి.',
  'moved_successfully': 'విజయవంతంగా తరలించబడింది!',
  'today': 'ఈ రోజు',
  'yesterday': 'నిన్న',
  'm_ago': 'నిమిషాల క్రితం',
  'h_ago': 'గంటల క్రితం',
  // Field Selector
  'select_plot': 'ప్లాట్‌ను ఎంచుకోండి',
  'switch_plot_hint': 'ప్లాట్ మార్చడానికి తాకండి',
  'select_farming_plot': 'వ్యవసాయ ప్లాట్‌ను ఎంచుకోండి',
  'plot_environment_hint': 'AgriPulse అన్ని AI సలహాలను ఎంచుకున్న ప్లాట్ వాతావరణానికి అనుగుణంగా ఇస్తుంది.',
  'main_plot_north': 'ప్రధాన ప్లాట్ (ఉత్తర)',
  'unassigned_legacy_data': 'సాధారణ విచారణ',
  'unknown_crop': 'తెలియని పంట',
  'mixed_soil': 'మిశ్రమ నేల',
  'activity_log': 'కార్యాచరణ లాగ్',
  'search_history_hint': 'చరిత్రను శోధించండి...',
  'detailed_report': 'వివరణాత్మక నివేదిక',
  'select_record_detail': 'వివరాలను చూడటానికి రికార్డును ఎంచుకోండి',
  'detailed_data_unavailable': 'ఈ చారిత్రక రికార్డు కోసం వివరణాత్మక డేటా అందుబాటులో లేదు.',
  'run_new_prediction_hint': 'పూర్తి వివరాలను చూడటానికి దయచేసి కొత్త అంచనాను అమలు చేయండి.',
  'health_status': 'ఆరోగ్య స్థితి',
  'diagnosis_analysis': 'రోగనిర్ధారణ విశ్లేషణ',
  'severity_score': 'తీవ్రత స్కోర్',
  'severity_high': 'అధిక',
  'severity_medium': 'మధ్యస్థ',
  'severity_low': 'తక్కువ',
  'environmental_status': 'పర్యావరణ స్థితి',
  'confidence_metrics': 'విశ్వాస కొలమానాలు',
  'ai_recommendation': 'AI సిఫార్సు',
  'soil_correction': 'నేల సవరణ',
  'model_precision': 'మోడల్ ఖచ్చితత్వం',
  'verified_ai': 'AgriPulse AI ద్వారా ధృవీకరించబడింది',
  'findings': 'రోగనిర్ధారణ ఫలితాలు',
  'confidence_score_cap': 'విశ్వాస స్కోర్',
  'qtl_acre': 'క్విం/ఎకరా',
  'clear_history': 'చరిత్రను క్లియర్ చేయండి',
  'clear_history_confirm': 'మీరు ఖచ్చితంగా మొత్తం చరిత్రను క్లియర్ చేయాలనుకుంటున్నారా?',
  'delete_plot': 'ప్లాట్‌ని తొలగించండి',
  'delete_plot_confirm': 'మీరు ఖచ్చితంగా ఈ ప్లాట్‌ని తొలగించాలనుకుంటున్నారా?',
  'clear': 'క్లియర్',
  'cancel': 'రద్దు చేయండి',
  'market_insights': 'మార్కెట్ అంతర్దృష్టులు',
  'treatment_plan': 'చికిత్స ప్రణాళిక',
  'humidity': 'తేమ',
  'confidence_level': 'విశ్వాస స్థాయి',
  'jan': 'జనవరి',
  'feb': 'ఫిబ్రవరి',
  'mar': 'మార్చి',
  'apr': 'ఏప్రిల్',
  'may': 'మే',
  'jun': 'జూన్',
  'jul': 'జూలై',
  'aug': 'ఆగస్టు',
  'sep': 'సెప్టెంబరు',
  'oct': 'అక్టోబరు',
  'nov': 'నవంబరు',
  'dec': 'డిసెంబరు',
  'analysis_failed_connection': 'విశ్లేషణ విఫలమైంది. కనెక్షన్ లోపం.',
  'refinement_failed': 'మరింత మెరుగుపరచడం విఫలమైంది',
  'audio_empty_error': 'సర్వర్ నుండి ఖాళీ ఆడియో వచ్చింది.',
  'audio_play_failed': 'సలహా వినిపించడంలో విఫలమైంది',
  'unknown_issue': 'తెలియని సమస్య',
  'consult_expert': 'నిపుణుడిని సంప్రదించండి.',
  'no_advice_available': 'ఏ సలహా అందుబాటులో లేదు.',
  'diagnosis_prefix': 'నిర్ధారణ',
  'recommendation_prefix': 'సిఫార్సు',
  'scan_in': 'స్కాన్:',
  'irrigation_stage': 'నీటి పారుదల దశ',
  'weather_events': 'వాతావరణ సంఘటనలు',
  'spread_pattern': 'వ్యాప్తి నమూనా',
  'intervention_log': 'జోక్యాల లాగ్',
  'establishment': 'స్థాపన',
  'sprouting': 'మొలకలెత్తడం',
  'leaf_dev': 'ఆకు అభివృద్ధి',
  'bulb_init': 'కంద ప్రారంభిక',
  'bulb_dev': 'కంద అభివృద్ధి',
  'bone_dry': 'పూర్తిగా ఎండిన',
  'moist': 'తేమగా ఉన్న',
  'waterlogged': 'నీరు నిలిచిన',
  'frost': 'మంచు',
  'heavy_rain': 'భారీ వర్షం',
  'drizzle': 'చినుకులు',
  'wind': 'గాలి',
  'too_hot': 'చాలా వేడి',
  'isolated': 'వేరు చేయబడిన',
  'localized': 'స్థానికీకరించిన',
  'field_wide': 'పొలం అంతటా',
  'last_treatment': 'చివరిగా వాడినది',
  'dosage': 'మోతాదు',
  'fert_organic': 'సేంద్రీయ',
  'fert_npk': 'NPK',
  'fungicide': 'శిలీంద్రనాశిని',
  'insecticide': 'కీటకనాశిని',
  'low': 'తక్కువ',
  'medium': 'మధ్యస్థం',
  'high': 'ఎక్కువ',
  'workspace_context': 'క్షేత్ర సందర్భం',
  'leaf_texture': 'ఆకు ఆకృతి',
  'texture_brittle': 'పెళుసైన',
  'texture_slimy': 'జిగటగా ఉండే',
  'texture_rubbery': 'రబ్బరు లాంటి',
  'odor_presence': 'వాసన ఉనికి',
  'odor_foul': 'దుర్వాసన',
  'odor_none': 'వాసన లేదు',
  'speed_of_spread': 'వ్యాప్తి వేగం',
  'spread_overnight': 'రాత్రికి రాత్రే కనిపించింది',
  'spread_slow': 'నెమ్మదిగా వ్యాపిస్తోంది',
  'role_user': 'మీరు',
  'role_ai': 'AgriPulse AI',
  'analysis_complete': 'విశ్లేషణ పూర్తయింది',
  'default_ai_response': 'మీ అభిప్రాయం ఆధారంగా నవీకరించబడిన నిర్ధారణ.',
  'treatment_adjustment_label': 'సర్దుబాటు',
  'sidebar_waiting_hint': 'విశ్లేషణ కోసం వేచి ఉంది... అది కనిపించిన తర్వాత AI నిర్ధారణను మెరుగుపరచడానికి ఈ విభాగాన్ని ఉపయోగించండి.',
  'view_report': 'నివేదికను చూడండి',
  'initial_request': 'ప్రారంభ అభ్యర్థన',
  'initial_diagnosis': 'ప్రారంభ నిర్ధారణ',
  'refined_diagnosis': 'మెరుగుపరచబడిన నిర్ధారణ',
  'refinement_reasoning': 'మెరుగుదల తర్కం',
  'refinement_feedback': 'మెరుగుదల అభిప్రాయం',
  'ai_findings': 'AI విశ్లేషణ ఫలితాలు',
  'adjusted_treatment_plan': 'సర్దుబాటు చేసిన చికిత్స ప్రణాళిక',
  'view_standard_treatment': 'ప్రామాణిక చికిత్సను చూడండి',
  'view_adjusted_plan': 'సర్దుబాటు చేసిన ప్రణాళికను చూడండి',
  'delete': 'తీసివేయి',
  'delete_record_confirm': 'ఈ రికార్డును తీసివేయాలని మీరు ఖచ్చితంగా అనుకుంటున్నారా?',
  'record_deleted': 'రికార్డు తీసివేయబడింది',
  'prediction': 'అంచనా',
  'forecast': 'మున్సూచన',
};
