const Map<String, String> tamilTranslations = {
  'yield_prediction': 'மகசூல் முன்னறிவிப்பு',
  'predict_harvest': 'உங்கள் அறுவடையை கணித்திடுங்கள்',
  'enter_details': 'AI-இயங்கும் மகசூல் கணிப்பிற்கு உங்கள் வயல் விவரங்களை உள்ளிடவும்.',
  'crop_details': 'பயிர் விவரங்கள்',
  'field_name': 'வயலின் பெயர்',
  'crop_name': 'பயிரின் பெயர்',
  'field_area': 'வயல் பரப்பு (ஏக்கர்)',
  'environment': 'சுற்றுச்சூழல்',
  'soil_type': 'மண் வகை',
  'planted_date': 'நடவு செய்த தேதி',
  'get_prediction': 'கணிப்பைப் பெறுங்கள்',
  'gemini_hint': 'ஜெமினி 3.0 ப்ரோ நிகழ்நேர வானிலை முன்னறிவிப்புகளுடன் இந்தக் காரணிகளை பகுப்பாய்வு செய்யும்.',
  'yield_forecast': 'மகசூல் கணிப்பு',
  'confidence': 'நம்பிக்கை',
  'core_factors': 'முக்கிய காரணிகள்',
  'ai_strategy': 'AI உத்தி',
  'onion': 'வெங்காயம்',
  'tomato': 'தக்காளி',
  'potato': 'உருளைக்கிழங்கு',
  'rice': 'நெல்',
  'wheat': 'கோதுமை',
  'maize': 'சோளம்',
  'cotton': 'பருத்தி',
  'sugarcane': 'கரும்பு',
  'clay_loam': 'களிமண் கலந்த மண்',
  'sandy_soil': 'மணல் மண்',
  'sandy_loam': 'மணல் கலந்த மண்',
  'red_loamy': 'சிவப்பு நிறமுள்ள மண்',
  'black_cotton': 'கருப்பு பருத்தி மண்',
  'silt_loam': 'வண்டல் மண்',
  'peat': 'கரிம மண்',
  'chalky': 'சுண்ணாம்பு மண்',
  'black_soil': 'கரிசல் மண்',
  'red_soil': 'செம்மண்',
  'acres': 'ஏக்கர்',
  'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
  'language': 'மொழி',
  'yield_outlook': '7-நாள் மகசூல் பார்வை',
  'good_potential': 'நல்ல மகசூல் திறன்',
  'climatic_stress': 'வானிலை பாதிப்பு',
  'field_parameters': 'வயல் அளவுருக்கள்',
  'system_health': 'சிஸ்டம் ஆரோக்கியம்',
  'active_feed': 'செயலில் உள்ள ஊட்டம்:',
  'api_stable': 'வானிலை_ஏபிஐ_நிலைத்தன்மை',
  'estimated_yield': 'மதிப்பிடப்பட்ட மகசூல்',
  'low_reliability': 'குறைந்த நம்பகத்தன்மை',
  'medium_reliability': 'நடுத்தர நம்பகத்தன்மை',
  'high_reliability': 'அதிக நம்பகத்தன்மை',
  'yield_trajectory': '7-நாள் மகசூல் பாதை',
  'contextual_insights': 'சூழல் சார்ந்த நுண்ணறிவு',
  'temperature': 'வெப்பநிலை',
  'soil_moisture': 'மண் ஈரம்',
  'disease_risk': 'நோய் அபாயம்',
  'sunlight': 'சூரிய ஒளி',
  'optimal': 'உகந்தது',
  'monitor': 'கண்காணிக்கவும்',
  'warning': 'எச்சரிக்கை',
  'good': 'நல்லது',
  'diffuse': 'பரவலான',
  'expected_harvest_date': 'எதிர்பார்க்கப்படும் அறுவடை தேதி',
  'run_prediction': 'கணிப்பை இயக்கவும்',
  'harvest_window_warning': 'குறிப்பு: அறுவடை தேதி 14 நாள் வானிலை கணிப்புக்கு அப்பால் உள்ளது. AI காலநிலையை அடிப்படையாகக் கொண்டு கணிக்கும்.',
  'financial_outlook': 'நிதி பார்வை',
  'projected_revenue': 'திட்டமிடப்பட்ட வருவாய்',
  'estimated_cost': 'மதிப்பிடப்பட்ட செலவு',
  'net_profit': 'நிகர லாபம்',
  'financial_disclaimer': '* {cropName}-க்கான தற்போதைய சந்தை சராசரியின் அடிப்படையிலான மதிப்பீடுகள். உண்மையான வருமானம் மாறுபடலாம்.',
  'hello': 'வணக்கம்',
  'smart_tools': 'ஸ்மார்ட் கருவிகள்',
  'crop_doctor': 'பயிர் மருத்துவர்',
  'crop_doctor_desc': 'AI தாவர சுகாதாரம்/நோய் கண்டறிதல்',
  'yield_est': 'மகசூல் கணிப்பு',
  'yield_est_desc': 'வானிலை அடிப்படையில் கணிப்பு',
  'market': 'சந்தை',
  'market_desc': 'நேரடி விலை & போக்குகள்',
  'ask_expert': 'நிபுணரிடம் கேளுங்கள்',
  'ask_expert_desc': '24/7 விவசாய ஆலோசனை',
  
  // Coming Soon Features
  'coming_soon': 'விரைவில் வருகிறது',
  'soil_health_time_machine': 'மண் ஆரோக்கிய டைம்-மெஷின்',
  'soil_health_desc': 'மண் மாற்றங்களைக் கண்காணிக்கவும்',
  'market_analysis': 'சந்தை பகுப்பாய்வு',
  'market_analysis_desc': 'பயிர் விலை போக்குகள்',
  'smart_irrigation': 'ஸ்மார்ட் நீர்ப்பாசன திட்டமிடுபவர்',
  'smart_irrigation_desc': 'AI நீர் மேம்படுத்தல்',
  'voice_command': 'குரல்-மட்டும் கட்டளை மையம்',
  'voice_command_desc': 'கைகள் இலவச செயல்பாடு',
  'support_24_7': '24/7 ஆதரவு',
  'support_24_7_desc': 'உடனடி நிபுணர் உதவி',
  'sustainable_farming': 'நிலையான விவசாயம்',
  'sustainable_farming_desc': 'சுற்றுச்சூழல் நட்பு நடைமுறைகள்',
  'community_alert': 'சமூக எச்சரிக்கை',
  'community_alert_desc': 'உள்ளூர் பூச்சி எச்சரிக்கைகள்',
  'government_schemes': 'அரசு திட்டங்கள்',
  'government_schemes_desc': 'மானியங்கள் மற்றும் நன்மைகள்',
  'onboarding_tutorials': 'ஆன்போர்டிங் பயிற்சிகள்',
  'onboarding_tutorials_desc': 'படிப்படியான வழிகாட்டிகள்',
  
  'rice_field': 'நெல் வயல்',
  'wheat_field': 'கோதுமை வயல்',
  'corn_field': 'சோள வயல்',
  'onion_field': 'வெங்காய வயல்',
  'tomato_field': 'தக்காளி வயல்',
  'cotton_field': 'பருத்தி வயல்',
  'sugarcane_field': 'கரும்பு வயல்',
  'vegetable_patch': 'காய்கறி தோட்டம்',
  'custom_input': 'தனிப்பயன்',
  'acreage_small': '< 1 ஏக்கர்',
  'acreage_medium': '1-2 ஏக்கர்',
  'acreage_large': '2-5 ஏக்கர்',
  'acreage_very_large': '5-10 ஏக்கர்',
  'acreage_estate': '> 10 ஏக்கர்',
  'login_skip_demo': 'உள்நுழைவைத் தவிர்க்கவும் (டெமோ)',
  'login_tagline': 'உங்கள் அறிவார்ந்த விவசாய துணை',
  'login_title': 'விவசாயி நுழைவு',
  'login_otp_title': 'சரிபார்ப்பு குறியீட்டை உள்ளிடவும்',
  'login_phone_label': 'தொலைபேசி எண்',
  'login_phone_hint': '98765 43210',
  'login_send_otp': 'OTP அனுப்பவும்',
  'login_otp_sent_to': 'அனுப்பப்பட்டது',
  'login_verify': 'சரிபார்த்து உள்நுழையவும்',
  'login_change_number': 'எண்ணை மாற்றவும்',
  'login_powered_by': 'Gemini 3.0 மூலம் இயக்கப்படுகிறது',
  'upload_crop_image': 'பயிர் படத்தை பதிவேற்றவும்',
  'take_photo_instruction': 'பாதிக்கப்பட்ட பகுதியின் தெளிவான புகைப்படத்தை எடுக்கவும்',
  'upload_image': 'படத்தை பதிவேற்றவும்',
  'supports_formats': 'ஆதரிக்கிறது: JPG, PNG',
  'camera': 'கேமரா',
  'gallery': 'கேலரி',
  'analyze_crop': 'பயிரை பகுப்பாய்வு செய்யவும்',
  'analyzing': 'பகுப்பாய்வு செய்கிறது...',
  'identifying_diseases': 'நோய்களை கண்டறிகிறது',
  'diagnosis_results': 'கண்டறிதல் முடிவுகள்',
  'diagnosis_placeholder': 'படத்தை பதிவேற்றி பகுப்பாய்வு செய்யவும்',
  'detected_issue': 'கண்டறியப்பட்ட பிரச்சனை',
  'healthy_plant': 'ஆரோக்கியமான தாவരം',
  'recommended_treatment': 'பரிந்துரைக்கப்பட்ட சிகிச்சை',
  'generate_report': 'அறிக்கை உருவாக்கவும்',
  'listen_advice': 'ஆலோசனை கேளுங்கள்',
  'playing_advice': 'ஆலோசனை ஒலிக்கிறது...',
  'getting_audio': 'ஆடியோவைப் பெறுகிறது...',
  'describe_issue_hint': 'பிரச்சனையை விவரிக்கவும்',
  'climate_aware_forecasting': 'காலநிலை-அறிவுள்ள முன்னறிவிப்பு',
  'ai_engine_reasoning': 'உங்கள் வயல் விவரங்களை வழங்கியதும், எங்கள் AI இன்ஜின் ஜெமினி 3.0 ப்ரோவைப் பயன்படுத்தி இவற்றில் பல காரணிகளை ஆய்வு செய்யும்:',
  'reasoning_factor_1': 'உள்ளூர் 7-நாள் வானிலை முன்னறிவிப்புகள்',
  'reasoning_factor_2': 'பயிர் சார்ந்த வளர்ச்சி சுழற்சிகள்',
  'reasoning_factor_3': 'மண் வள மாதிரிகள்',
  'reasoning_factor_4': 'பிராந்திய வரலாறு',
  'challenge_diagnosis': 'நோயறிதலை சவால் செய்',
  'ai_reasoning': 'AI காரணம்',
  'soil_condition': 'மண் நிலை',
  'weather_condition': 'வானிலை நிலை',
  'missed_info_hint': 'நான் எதைத் தவறவிட்டேன்?',
  'provide_feedback_error': 'தயவுசெய்து கருத்து தெரிவிக்கவும்.',
  'soil_normal': 'இயல்பு',
  'soil_dry': 'வறண்ட/மணல்',
  'soil_wet': 'ஈரமான/களிமண்',
  'soil_log': 'நீர் தேங்கிய',
  'weather_sunny': 'வெயில்',
  'weather_cloudy': 'மேகமூட்டம்',
  'weather_rain': 'கனமழை',
  'weather_windy': 'காற்று',
  'refining': 'மேம்படுத்துகிறது...',
  'ask_second_opinion': 'இரண்டாவது கருத்தைக் கேளுங்கள்',
  'select_harvest_date': 'தயவுசெய்து முதலில் அறுவடை தேதியைத் தேர்ந்தெடுக்கவும்.',
  'prediction_failed': 'முன்னறிவிப்பு தோல்வியடைந்தது',
  'retry': 'மீண்டும் முயற்சிக்கவும்',
  'soil_and_environment': 'மண் மற்றும் சுற்றுச்சூழல்',
  'help_gemini_understand': 'உங்கள் நிலத்தைப் பற்றி ஜெமினி புரிந்துகொள்ள உதவவும்.',
  'select_soil_texture': 'மண் வகையைத் தேர்ந்தெடுக்கவும்',
  'irrigation_method': 'நீர்ப்பாசன முறை',
  'how_do_you_water': 'உங்கள் பயிர்களுக்கு எப்படி தண்ணீர் பாய்ச்சுகிறீர்கள்?',
  'welcome_agripulse': 'AgriPulse-க்கு வரவேற்கிறோம்',
  'setup_first_plot': 'தனிப்பயனாக்கப்பட்ட AI ஆலோசனையைப் பெற உங்கள் முதல் பண்ணை நிலத்தை அமைக்கவும்.',
  'plot_name': 'நிலத்தின் பெயர்',
  'approx_acreage': 'தோராயமான ஏக்கர்',
  'continue': 'தொடரவும்',
  'finish_setup': 'அமைப்பை முடிக்கவும்',
  'my_first_plot': 'எனது முதல் நிலம்',
  'register_new_plot': 'புதிய நிலத்தை பதிவு செய்யவும்',
  'plot_info': 'நிலத்தின் விவரங்கள்',
  'ground_advice_hint': 'நில விவரங்களை வழங்குவதன் மூலம் AgriPulse அதன் ஆலோசனையை மேம்படுத்த உதவவும்.',
  'submit_registration': 'பதிவைச் சமர்ப்பிக்கவும்',
  'drip': 'சொட்டு நீர் பாசனம்',
  'sprinkler': 'தெளிப்பு நீர் பாசனம்',
  'manual_bucket': 'கைமுறை / வாலி மூலம்',
  'flood': 'மடை நீர்ப்பாசனம்',
  'rain_fed': 'மழைநீர் பாசனம்',
  'clay_loam_desc': 'சிறந்த நீர் தக்கவைப்பு, அதிக ஊட்டச்சத்துக்கள்.',
  'sandy_soil_desc': 'வேகமான வடிகால், அடிக்கடி நீர்ப்பாசனம் தேவை.',
  'red_loamy_desc': 'சீரான வடிகால், பெரும்பாலான பயிர்களுக்கு நல்லது.',
  'black_cotton_desc': 'அதிக ஈரப்பதம் கொள்ளளவு, பருத்தி/வெங்காயத்திற்கு சிறந்தது.',
  'recent_activity': 'சமீபத்திய செயல்பாடு',
  'see_all': 'அனைத்தையும் காண்க',
  'error_loading_activity': 'செயல்பாட்டை ஏற்றுவதில் பிழை',
  'move_to_plot': 'ஒரு நிலத்திற்கு மாற்றவும்',
  'no_activity_yet': 'இதுவரை எந்த செயல்பாடும் இல்லை',
  'start_scan_prediction_hint': 'வரலாற்றைக் காண பயிர் ஸ்கேன் அல்லது மகசூல் கணிப்பைத் தொடங்கவும்',
  'move_record_to_plot': 'பதிவை நிலத்திற்கு மாற்றவும்',
  'select_destination_plot': 'இந்த செயல்பாட்டிற்கான இலக்கு நிலத்தைத் தேர்ந்தெடுக்கவும்.',
  'moved_successfully': 'வெற்றிகரமாக மாற்றப்பட்டது!',
  'today': 'இன்று',
  'tomorrow': 'நாளை',
  'yesterday': 'நேற்று',
  'm_ago': 'நிமி முன்',
  'h_ago': 'மணி முன்',
  // Field Selector
  'select_plot': 'நிலத்தைத் தேர்ந்தெடுக்கவும்',
  'switch_plot_hint': 'நிலத்தைச் மாற்ற இங்கே தொடவும்',
  'select_farming_plot': 'விவசாயத் நிலத்தைத் தேர்ந்தெடுக்கவும்',
  'plot_environment_hint': 'AgriPulse அனைத்து AI ஆலோசனைகளையும் தேர்ந்தெடுக்கப்பட்ட நிலச் சூழலுக்கு ஏற்ப வழங்கும்.',
  'main_plot_north': 'முக்கிய நிலம் (வடக்கு)',
  'unassigned_legacy_data': 'பொது விசாரணை',
  'unknown_crop': 'அறியப்படாத பயிர்',
  'mixed_soil': 'கலப்பு மண்',
  'activity_log': 'செயல்பாட்டு பதிவு',
  'search_history_hint': 'வரலாற்றைத் தேடுங்கள்...',
  'detailed_report': 'விரிவான அறிக்கை',
  'select_record_detail': 'விவரங்களைக் காண ஒரு பதிவைத் தேர்ந்தெடுக்கவும்',
  'detailed_data_unavailable': 'இந்த வரலாற்றுப் பதிவிற்கு விரிவான தரவு கிடைக்கவில்லை.',
  'run_new_prediction_hint': 'முழு விவரங்களைக் காண புதிய கணிப்பை இயக்கவும்.',
  'health_status': 'ஆரோக்கிய நிலை',
  'diagnosis_analysis': 'கண்டறிதல் பகுப்பாய்வு',
  'severity_score': 'தீவிரத்தன்மை அளவு',
  'severity_high': 'அதிகம்',
  'severity_medium': 'மிதமானது',
  'severity_low': 'குறைவு',
  'environmental_status': 'சுற்றுச்சூழல் நிலை',
  'confidence_metrics': 'நம்பகத்தன்மை அளவீடுகள்',
  'ai_recommendation': 'AI பரிந்துரை',
  'soil_correction': 'மண் திருத்தம்',
  'model_precision': 'மாதிரி துல்லியம்',
  'verified_ai': 'AgriPulse AI மூலம் சரிபார்க்கப்பட்டது',
  'findings': 'கண்டறியப்பட்ட முடிவுகள்',
  'confidence_score_cap': 'நம்பகத்தன்மை மதிப்பெண்',
  'qtl_acre': 'குவிண்டால்/ஏக்கர்',
  'clear_history': 'வரலாற்றை நீக்கு',
  'clear_history_confirm': 'அனைத்து வரலாற்றையும் நிச்சயமாக அழிக்க விரும்புகிறீர்களா?',
  'delete_plot': 'நிலத்தை நீக்கு',
  'delete_plot_confirm': 'இந்த நிலத்தை நீக்க விரும்புகிறீர்களா (அனைத்து தரவுகளும் இழக்கப்படும்)?',
  'clear': 'அழி',
  'cancel': 'ரத்துசெய்',
  'market_insights': 'சந்தை நுண்ணறிவு விவரங்கள்',
  'treatment_plan': 'சிகிச்சை திட்டம்',
  'humidity': 'காற்று ஈரப்பதம்',
  'confidence_level': 'நம்பிக்கை நிலை',
  'jan': 'ஜனவரி',
  'feb': 'பிப்ரவரி',
  'mar': 'மார்ச்',
  'apr': 'ஏப்ரல்',
  'may': 'மே',
  'jun': 'ஜூன்',
  'jul': 'ஜூலை',
  'aug': 'ஆகஸ்ட்',
  'sep': 'செப்டம்பர்',
  'oct': 'அக்டோபர்',
  'nov': 'நவம்பர்',
  'dec': 'டிசம்பர்',
  'analysis_failed_connection': 'பகுப்பாய்வு தோல்வியுற்றது. இணைப்புப் பிழை.',
  'refinement_failed': 'பரிசோதனை தோல்வியுற்றது',
  'audio_empty_error': 'சர்வரிலிருந்து காலியான ஆடியோ பெறப்பட்டது.',
  'audio_play_failed': 'ஆலோசனையை ஒலிக்கச் செய்வதில் தோல்வி',
  'unknown_issue': 'அறியப்படாத பிரச்சனை',
  'consult_expert': 'நிபுணரை அணுகவும்.',
  'no_advice_available': 'ஆலோசனை எதுவும் இல்லை.',
  'diagnosis_prefix': 'கண்டுபிடிப்பு',
  'recommendation_prefix': 'பரிந்துரை',
  'scan_in': 'ஸ்கேன்:',
  'irrigation_stage': 'நீர்ப்பாசன நிலை',
  'weather_events': 'வானிலை நிகழ்வுகள்',
  'spread_pattern': 'பரவல் முறை',
  'intervention_log': 'சிகிச்சை வரலாறு',
  'establishment': 'நிறுவுதல்',
  'sprouting': 'துளிர்விடுதல்',
  'leaf_dev': 'இலை வளர்ச்சி',
  'bulb_init': 'முளை ஆரம்ப நிலை',
  'bulb_dev': 'முளை வளர்ச்சி',
  'bone_dry': 'மிகவும் காய்ந்த',
  'moist': 'ஈரப்பதமான',
  'waterlogged': 'தேங்கிய நீர்',
  'frost': 'உறைபனி',
  'heavy_rain': 'கனமழை',
  'drizzle': 'தூறல்',
  'wind': 'காற்று',
  'too_hot': 'அதிக வெப்பம்',
  'isolated': 'தனிமைப்பட்ட',
  'localized': 'உள்ளூர்',
  'field_wide': 'வயல் முழுவதும்',
  'last_treatment': 'கடைசியாக பயன்படுத்தியது',
  'dosage': 'அளவு',
  'fert_organic': 'இயற்கை உரம்',
  'fert_npk': 'NPK',
  'fungicide': 'பூஞ்சை காளான்',
  'insecticide': 'பூச்சிக்கொல்லி',
  'low': 'குறைந்த',
  'medium': 'நடுத்தர',
  'high': 'அதிக',
  'workspace_context': 'புல சூழல்',
  'leaf_texture': 'இலை அமைப்பு',
  'texture_brittle': 'உடையக்கூடிய/மொறுமொறுப்பான',
  'texture_slimy': 'வழுவழுப்பான/மென்மையான',
  'texture_rubbery': 'ரப்பர் போன்ற/கடினமான',
  'odor_presence': 'வாசனை இருப்பு',
  'odor_foul': 'துர்நாற்றம்/அழுகிய',
  'odor_none': 'வாசனை இல்லை',
  'speed_of_spread': 'பரவலின் வேகம்',
  'spread_overnight': 'ஒரே இரவில் தோன்றியது',
  'spread_slow': 'மெதுவாக வளர்கிறது (2+ வாரங்கள்)',
  // Recursive Insight
  'role_user': 'நீங்கள்',
  'role_ai': 'AgriPulse AI',
  'analysis_complete': 'பகுப்பாய்வு முடிந்தது',
  'default_ai_response': 'உங்கள் பின்னூட்டத்தின் அடிப்படையில் புதுப்பிக்கப்பட்ட நோய் கண்டறிதல்.',
  'treatment_adjustment_label': 'திருத்தம்',
  'sidebar_waiting_hint': 'பகுப்பாய்வுக்காகக் காத்திருக்கிறது... AI நோயறிதல் தோன்றியவுடன் அதைச் செம்மைப்படுத்த இந்தப் பகுதியைப் பயன்படுத்தவும்.',
  'view_report': 'அறிக்கையைப் பார்க்கவும்',
  'initial_request': 'ஆரம்பக் கோரிக்கை',
  'initial_diagnosis': 'ஆரம்ப நோயறிதல்',
  'refined_diagnosis': 'செம்மைப்படுத்தப்பட்ட நோயறிதல்',
  'refinement_reasoning': 'சுத்திகரிப்பு பகுத்தறிவு',
  'refinement_feedback': 'சுத்திகரிப்பு பின்னூட்டம்',
  'ai_findings': 'AI கண்டுபிடிப்புகள்',
  'adjusted_treatment_plan': 'சரிசெய்யப்பட்ட சிகிச்சை திட்டம்',
  'view_standard_treatment': 'நிலையான சிகிச்சையைப் பார்க்கவும்',
  'view_adjusted_plan': 'சரிசெய்யப்பட்ட திட்டத்தைக் காண்க',
  'delete': 'நீக்கு',
  'delete_record_confirm': 'இந்த பதிவை நீக்க விரும்புகிறீர்களா?',
  'record_deleted': 'பதிவு நீக்கப்பட்டது',
  'prediction': 'கணிப்பு',
  'forecast': 'முன்னறிவிப்பு',
  'diagnosis_report': 'நோய் கண்டறிதல் அறிக்கை',
  'date_label': 'தேதி:',
  'disease_label': 'நோய்:',
  'confidence_label': 'நம்பிக்கை:',
  'diagnostic_findings_title': 'நோய் கண்டறிதல் கண்டுபிடிப்புகள்',
  'standard_treatment_plan': 'நிலையான சிகிச்சை திட்டம்:',
  'treatment_adjustments': 'சிகிச்சை சரிசெய்தல்',
  'sharing_report': 'அறிக்கை பகிரப்படுகிறது...',
  'downloading_pdf': 'PDF பதிவிறக்கம் செய்யப்படுகிறது...',
  'download_pdf_button': 'PDF பதிவிறக்கம் செய்க',
  'share_button': 'பகிர்',
  'severity': 'தீவிரம்',
  'temp': 'வெப்பநிலை',
  'moisture': 'மண் ஈரப்பதம்',
  'analysis_metrics': 'பகுப்பாய்வு அளவீடுகள்',
  'evidence': 'ஆதாரம்',
  'analyzed_evidence': 'பகுப்பாய்வு செய்யப்பட்ட ஆதாரம்',
  'completed': 'முடிந்தது',
  'no_feedback_provided': 'கருத்து எதுவும் வழங்கப்படவில்லை',
  'share': 'பகிர்',
  'verifying_securely': 'பாதுகாப்பாக சரிபார்க்கப்படுகிறது...',
  'offline_mode_warning': 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள். சேமிக்கப்பட்ட தரவு காட்டப்படுகிறது.',
  'yield_prediction_failed': 'மகசூல் கணிப்பு தோல்வியடைந்தது',
  'select_params_warning': 'கணிப்பை இயக்குவதற்கு முன் அனைத்து அளவுருக்களையும் தேர்ந்தெடுக்கவும்.',
  'confidence_suffix': 'CONF',
  // Single-page onboarding
  'welcome_setup_first_plot': 'வரவேற்கிறோம்! உங்கள் முதல் நிலத்தை அமைப்போம்',
  'skip_demo': 'பதிவை தவிர்க்கவும் (டெமோ)',
  'demo_plot_name': 'டெமோ நிலம்',
  'unlock_ai_insights': 'AI-இயங்கும் விவசாய நுண்ணறிவுகளை திறக்க உங்கள் முதல் நிலத்தை அமைக்கவும்',
  'get_started': 'தொடங்குங்கள்',
  // Plot deletion
  'delete_only_plot_warning': 'இது உங்கள் ஒரே நிலம். இதை நீக்குவதற்கு பயன்பாட்டைப் பயன்படுத்துவதற்கு முன் புதிய நிலத்தை அமைக்க வேண்டும்.',
  'redirect_to_setup_hint': 'நீக்கிய பிறகு நீங்கள் நில அமைப்புக்கு திருப்பி விடப்படுவீர்கள்.',
};
