const Map<String, String> englishTranslations = {
  'yield_prediction': 'Yield Prediction',
  'predict_harvest': 'Predict Your Harvest',
  'enter_details': 'Enter your field details for an AI-powered yield estimation.',
  'crop_details': 'Crop Details',
  'field_name': 'Field Name',
  'crop_name': 'Crop Name',
  'field_area': 'Field Area (Acres)',
  'environment': 'Environment',
  'soil_type': 'Soil Type',
  'planted_date': 'Planted Date',
  'get_prediction': 'Get Prediction',
  'gemini_hint': 'Gemini 3.0 Pro will analyze these factors against real-time weather forecasts.',
  'yield_forecast': 'Yield Forecast',
  'confidence': 'Confidence',
  'core_factors': 'Core Factors',
  'ai_strategy': 'AI Strategy',
  'onion': 'Onion',
  'tomato': 'Tomato',
  'potato': 'Potato',
  'rice': 'Rice',
  'wheat': 'Wheat',
  'maize': 'Maize',
  'cotton': 'Cotton',
  'sugarcane': 'Sugarcane',
  'clay_loam': 'Clay Loam',
  'sandy_soil': 'Sandy Soil',
  'sandy_loam': 'Sandy Loam',
  'red_loamy': 'Red Loamy Soil',
  'black_cotton': 'Black Cotton Soil',
  'silt_loam': 'Silt Loam',
  'peat': 'Peat',
  'chalky': 'Chalky',
  'black_soil': 'Black Soil',
  'red_soil': 'Red Soil',
  'acres': 'Acres',
  'select_language': 'Select Language',
  'language': 'Language',
  'yield_outlook': '7-Day Yield Outlook',
  'good_potential': 'Good Potential',
  'climatic_stress': 'Climatic Stress',
  'field_parameters': 'Field Parameters',
  'system_health': 'System Health',
  'active_feed': 'ACTIVE FEED:',
  'api_stable': 'WEATHER_API_STABLE',
  'estimated_yield': 'ESTIMATED YIELD',
  'low_reliability': 'Low Reliability',
  'medium_reliability': 'Medium Reliability',
  'high_reliability': 'High Reliability',
  'yield_trajectory': '7-Day Yield Trajectory',
  'contextual_insights': 'Contextual Insights',
  'temperature': 'TEMPERATURE',
  'soil_moisture': 'SOIL MOISTURE',
  'disease_risk': 'DISEASE RISK',
  'sunlight': 'SUNLIGHT',
  'optimal': 'Optimal',
  'monitor': 'Monitor',
  'warning': 'Warning',
  'good': 'Good',
  'diffuse': 'Diffuse',
  'expected_harvest_date': 'Expected Harvest Date',
  'run_prediction': 'Run Prediction',
  'harvest_window_warning': 'Note: Harvest date is beyond the 14-day reliable weather window. AI will use seasonal climate averages.',
  'financial_outlook': 'Financial Outlook',
  'projected_revenue': 'Projected Revenue',
  'estimated_cost': 'Est. Cost',
  'net_profit': 'Net Profit',
  'financial_disclaimer': '* Estimates based on current market averages for {cropName}. Actual returns may vary.',
  'hello': 'Hello',
  'smart_tools': 'Smart Tools',
  'crop_doctor': 'Crop Doctor',
  'crop_doctor_desc': 'AI-powered plant health diagnostics',
  'yield_est': 'Yield Est.',
  'yield_est_desc': 'Predict harvest with weather data',
  'market': 'Market',
  'market_desc': 'Live crop prices & trends',
  'ask_expert': 'Ask Expert',
  'ask_expert_desc': '24/7 agricultural guidance',
  
  // Coming Soon Features
  'coming_soon': 'Coming Soon',
  'soil_health_time_machine': 'Soil Health Time-Machine',
  'soil_health_desc': 'Track soil changes over time',
  'market_analysis': 'Market Analysis',
  'market_analysis_desc': 'Prices + Expense Tracker',
  'smart_irrigation': 'Smart Irrigation Scheduler',
  'smart_irrigation_desc': 'Optimize water usage',
  'voice_command': 'Voice-ONLY Command Center',
  'voice_command_desc': 'Hands-free farming',
  'support_24_7': '24/7 Support',
  'support_24_7_desc': 'Always here to help',
  'sustainable_farming': 'Sustainable Farming',
  'sustainable_farming_desc': 'Eco-friendly practices',
  'community_alert': 'Community Alert',
  'community_alert_desc': 'Stay informed together',
  'government_schemes': 'Government Schemes',
  'government_schemes_desc': 'Access benefits & subsidies',
  'onboarding_tutorials': 'Onboarding Tutorials',
  'onboarding_tutorials_desc': 'Learn the platform',
  
  'rice_field': 'Rice Field',
  'wheat_field': 'Wheat Field',
  'corn_field': 'Corn Field',
  'onion_field': 'Onion Field',
  'tomato_field': 'Tomato Field',
  'cotton_field': 'Cotton Field',
  'sugarcane_field': 'Sugarcane Field',
  'vegetable_patch': 'Vegetable Patch',
  'custom_input': 'Custom',
  'acreage_small': '< 1 Acre',
  'acreage_medium': '1-2 Acres',
  'acreage_large': '2-5 Acres',
  'acreage_very_large': '5-10 Acres',
  'acreage_estate': '> 10 Acres',
  'login_skip_demo': 'Skip Login (Demo)',
  'login_tagline': 'Your Intelligent Farming Companion',
  'login_title': 'Farmer Login',
  'login_otp_title': 'Enter Verification Code',
  'login_phone_label': 'Phone Number',
  'login_phone_hint': '98765 43210',
  'login_send_otp': 'Send OTP',
  'login_otp_sent_to': 'Sent to',
  'login_verify': 'Verify & Login',
  'login_change_number': 'Change Number',
  'login_powered_by': 'Powered by Gemini 3.0',
  'upload_crop_image': 'Upload Crop Image',
  'take_photo_instruction': 'Take a clear photo of the affected area',
  'upload_image': 'Upload Image',
  'supports_formats': 'Supports: JPG, PNG',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'analyze_crop': 'Analyze Crop',
  'analyzing': 'Analyzing Crop...',
  'identifying_diseases': 'Identifying potential diseases',
  'diagnosis_results': 'Diagnosis Results',
  'diagnosis_placeholder': 'Upload an image and click analyze\nto see detailed report here.',
  'detected_issue': 'Detected Issue',
  'healthy_plant': 'Healthy Plant',
  'recommended_treatment': 'Recommended Treatment',
  'generate_report': 'Generate Report',
  'listen_advice': 'Listen to advice',
  'playing_advice': 'Playing advice...',
  'getting_audio': 'Getting audio...',
  'describe_issue_hint': 'Describe issue (e.g., in Tamil/Telugu/Kannada/Malayalam/Hindi/English)',
  'climate_aware_forecasting': 'Climate-Aware Forecasting',
  'ai_engine_reasoning': 'Once you provide your field details, our AI Engine uses Gemini 3.0 Pro to perform multi-factor reasoning on:',
  'reasoning_factor_1': 'Local 7-day weather forecasts',
  'reasoning_factor_2': 'Crop-specific growth cycles',
  'reasoning_factor_3': 'Soil productivity models',
  'reasoning_factor_4': 'Regional history',
  'challenge_diagnosis': 'Challenge Diagnosis',
  'ai_reasoning': 'AI Reasoning',
  'soil_condition': 'Soil Condition',
  'weather_condition': 'Weather Condition',
  'missed_info_hint': 'What did I miss? (e.g., "Leaves are sticky")',
  'provide_feedback_error': 'Please provide context or feedback to refine.',
  'soil_normal': 'Normal',
  'soil_dry': 'Dry/Sandy',
  'soil_wet': 'Wet/Clay',
  'soil_log': 'Waterlogged',
  'weather_sunny': 'Sunny',
  'weather_cloudy': 'Cloudy',
  'weather_rain': 'Heavy Rain',
  'weather_windy': 'Windy',
  'refining': 'Refining...',
  'ask_second_opinion': 'Ask Second Opinion',
  'select_harvest_date': 'Please select an estimated harvest date first.',
  'prediction_failed': 'Prediction Failed',
  'retry': 'Retry',
  'soil_and_environment': 'Soil & Environment',
  'help_gemini_understand': 'Help Gemini understand your land.',
  'select_soil_texture': 'Select Soil Texture',
  'irrigation_method': 'Irrigation Method',
  'how_do_you_water': 'How do you water your crops?',
  'welcome_agripulse': 'Welcome to AgriPulse',
  'setup_first_plot': 'Let\'s set up your first farm plot to get personalized AI advice.',
  'plot_name': 'Plot Name',
  'approx_acreage': 'Approximate Acreage',
  'continue': 'Continue',
  'finish_setup': 'Finish Setup',
  'my_first_plot': 'My First Plot',
  'register_new_plot': 'Register New Plot',
  'plot_info': 'Plot Information',
  'ground_advice_hint': 'Help AgriPulse ground its advice by providing plot details.',
  'submit_registration': 'Submit Registration',
  'drip': 'Drip',
  'sprinkler': 'Sprinkler',
  'manual_bucket': 'Manual / Bucket',
  'flood': 'Flood Irrigation',
  'rain_fed': 'Rain-fed',
  'clay_loam_desc': 'EXCELLENT WATER RETENTION, HIGH NUTRIENTS.',
  'sandy_soil_desc': 'FAST DRAINAGE, REQUIRES FREQUENT IRRIGATION.',
  'red_loamy_desc': 'BALANCED DRAINAGE, GOOD FOR MOST CROPS.',
  'black_cotton_desc': 'HIGH MOISTURE CAPACITY, IDEAL FOR COTTON/ONIONS.',
  'recent_activity': 'Recent Activity',
  'see_all': 'See All',
  'error_loading_activity': 'Error loading activity',
  'move_to_plot': 'Move to a Plot',
  'no_activity_yet': 'No activity yet',
  'start_scan_prediction_hint': 'Start a crop scan or yield prediction to see history',
  'move_record_to_plot': 'Move Record to Plot',
  'select_destination_plot': 'Select the destination plot for this activity.',
  'moved_successfully': 'Moved successfully!',
  'today': 'Today',
  'tomorrow': 'Tomorrow',
  'yesterday': 'Yesterday',
  'm_ago': 'm ago',
  'h_ago': 'h ago',
  // Field Selector
  'select_plot': 'Select Plot',
  'switch_plot_hint': 'Touch to switch plot context',
  'select_farming_plot': 'Select Farming Plot',
  'plot_environment_hint': 'AgriPulse grounding all AI advice to the selected plot environment.',
  'main_plot_north': 'Main Plot (North)',
  'unassigned_legacy_data': 'General Enquiry',
  'unknown_crop': 'Unknown Crop',
  'mixed_soil': 'Mixed Soil',
  'activity_log': 'Activity Log',
  'search_history_hint': 'Search history...',
  'detailed_report': 'Detailed Report',
  'select_record_detail': 'Select a record to view details',
  'detailed_data_unavailable': 'Detailed data unavailable for this historical record.',
  'run_new_prediction_hint': 'Please run a new prediction to see full details.',
  'health_status': 'HEALTH STATUS',
  'diagnosis_analysis': 'DIAGNOSIS ANALYSIS',
  'severity_score': 'SEVERITY SCORE',
  'severity_high': 'High',
  'severity_medium': 'Medium',
  'severity_low': 'Low',
  'environmental_status': 'ENVIRONMENTAL STATUS',
  'confidence_metrics': 'CONFIDENCE METRICS',
  'ai_recommendation': 'AI RECOMMENDATION',
  'soil_correction': 'SOIL CORRECTION',
  'model_precision': 'Model Precision',
  'verified_ai': 'Verified by AgriPulse AI',
  'findings': 'Diagnostic Findings',
  'confidence_score_cap': 'CONFIDENCE SCORE',
  'qtl_acre': 'Qtl/Acre',
  'clear_history': 'Clear History',
  'clear_history_confirm': 'Are you sure you want to clear all history?',
  'delete_plot': 'Delete Plot',
  'delete_plot_confirm': 'Are you sure you want to delete this plot?',
  'clear': 'Clear',
  'cancel': 'Cancel',
  'market_insights': 'Market Insights',
  'treatment_plan': 'Treatment Plan',
  'humidity': 'Humidity',
  'confidence_level': 'Confidence Level',
  'jan': 'Jan',
  'feb': 'Feb',
  'mar': 'Mar',
  'apr': 'Apr',
  'may': 'May',
  'jun': 'Jun',
  'jul': 'Jul',
  'aug': 'Aug',
  'sep': 'Sep',
  'oct': 'Oct',
  'nov': 'Nov',
  'dec': 'Dec',
  'analysis_failed_connection': 'Analysis failed. Connection error.',
  'refinement_failed': 'Refinement failed',
  'audio_empty_error': 'Received empty audio bytes from server.',
  'audio_play_failed': 'Failed to play advice',
  'unknown_issue': 'Unknown Issue',
  'consult_expert': 'Consult an expert.',
  'no_advice_available': 'No advice available.',
  'diagnosis_prefix': 'Diagnosis',
  'recommendation_prefix': 'Recommendation',
  'scan_in': 'Scan in',
  'irrigation_stage': 'Irrigation Stage',
  'weather_events': 'Weather Events',
  'spread_pattern': 'Spread Pattern',
  'intervention_log': 'Intervention Log',
  'establishment': 'Establishment',
  'sprouting': 'Sprouting',
  'leaf_dev': 'Leaf Dev',
  'bulb_init': 'Bulb Init',
  'bulb_dev': 'Bulb Dev',
  'bone_dry': 'Bone Dry',
  'moist': 'Moist',
  'waterlogged': 'Waterlogged',
  'frost': 'Frost',
  'heavy_rain': 'Heavy Rain',
  'drizzle': 'Drizzle',
  'wind': 'Wind',
  'too_hot': 'Too Hot',
  'isolated': 'Isolated',
  'localized': 'Localized',
  'field_wide': 'Field-wide',
  'last_treatment': 'Last Applied',
  'dosage': 'Dosage',
  'fert_organic': 'Organic',
  'fert_npk': 'NPK',
  'fungicide': 'Fungicide',
  'insecticide': 'Insecticide',
  'low': 'Low',
  'medium': 'Medium',
  'high': 'High',
  'workspace_context': 'Field Context',
  'leaf_texture': 'Leaf Texture',
  'texture_brittle': 'Brittle/Crunchy',
  'texture_slimy': 'Slimy/Soft',
  'texture_rubbery': 'Rubbery/Hard',
  'odor_presence': 'Odor Presence',
  'odor_foul': 'Foul/Putrid',
  'odor_none': 'No smell',
  'speed_of_spread': 'Speed of Spread',
  'spread_overnight': 'Appeared overnight',
  'spread_slow': 'Growing slowly (2+ weeks)',
  // Recursive Insight
  'role_user': 'You',
  'role_ai': 'AgriPulse AI',
  'analysis_complete': 'Analysis Complete',
  'default_ai_response': 'Updated diagnosis based on your feedback.',
  'treatment_adjustment_label': 'Adjustment',
  'sidebar_waiting_hint': 'Waiting for analysis... Use this section to refine the AI diagnosis once it appears.',
  'view_report': 'View Report',
  'initial_request': 'Initial Request',
  'initial_diagnosis': 'Initial Diagnosis',
  'refined_diagnosis': 'Refined Diagnosis',
  'refinement_reasoning': 'Refinement Reasoning',
  'refinement_feedback': 'Refinement Feedback',
  'ai_findings': 'AI Findings',
  'adjusted_treatment_plan': 'Adjusted Treatment Plan',
  'view_standard_treatment': 'View Standard Treatment',
  'view_adjusted_plan': 'View Adjusted Plan',
  'delete': 'Delete',
  'delete_record_confirm': 'Are you sure you want to remove this record?',
  'record_deleted': 'Record deleted',
  'prediction': 'Prediction',
  'forecast': 'Forecast',
  'diagnosis_report': 'Diagnosis Report',
  'date_label': 'Date:',
  'disease_label': 'Disease:',
  'confidence_label': 'Confidence:',
  'diagnostic_findings_title': 'DIAGNOSTIC FINDINGS',
  'standard_treatment_plan': 'Standard Treatment Plan:',
  'treatment_adjustments': 'Treatment Adjustments',
  'sharing_report': 'Sharing Report...',
  'downloading_pdf': 'Downloading PDF...',
  'download_pdf_button': 'Download PDF',
  'share_button': 'Share',
  'severity': 'Severity',
  'temp': 'Temp',
  'moisture': 'Moisture',
  'analysis_metrics': 'Analysis Metrics',
  'evidence': 'Evidence',
  'analyzed_evidence': 'Analyzed Evidence',
  'completed': 'Completed',
  'no_feedback_provided': 'No feedback provided',
  'share': 'Share',
  'verifying_securely': 'Verifying securely...',
  'offline_mode_warning': 'You are offline. Showing cached data.',
  'yield_prediction_failed': 'Yield prediction failed',
  'select_params_warning': 'Please select all field parameters before running prediction.',
  'confidence_suffix': 'CONF',
  // Single-page onboarding
  'welcome_setup_first_plot': 'Welcome! Let\'s set up your first plot',
  'skip_demo': 'Skip Registration (Demo)',
  'demo_plot_name': 'Demo Plot',
  'unlock_ai_insights': 'Set up your first plot to unlock AI-powered farming insights',
  'get_started': 'Get Started',
  // Plot deletion
  'delete_only_plot_warning': 'This is your only plot. Deleting it will require you to set up a new plot before using the app.',
  'redirect_to_setup_hint': 'You\'ll be redirected to plot setup after deletion.',
};
