const Map<String, String> kannadaTranslations = {
  'yield_prediction': 'ಇಳುವರಿ ಮುನ್ಸೂಚನೆ',
  'predict_harvest': 'ನಿಮ್ಮ ಸುಗ್ಗಿಯನ್ನು ಊಹಿಸಿ',
  'enter_details': 'AI-ಚಾಲಿತ ಇಳುವರಿ ಅಂದಾಜುಗಾಗಿ ನಿಮ್ಮ ಹೊಲದ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.',
  'crop_details': 'ಬೆಳೆ ವಿವರಗಳು',
  'field_name': 'ಹೊಲದ ಹೆಸರು',
  'crop_name': 'ಬೆಳೆಯ ಹೆಸರು',
  'field_area': 'ಹೊಲದ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)',
  'environment': 'ಪರಿಸರ',
  'soil_type': 'ಮಣ್ಣಿನ ವಿಧ',
  'planted_date': 'ನಾಟಿ ಮಾಡಿದ ದಿನಾಂಕ',
  'get_prediction': 'ಮುನ್ಸೂಚನೆ ಪಡೆಯಿರಿ',
  'gemini_hint': 'ಜೆಮಿನಿ 3.0 ಪ್ರೊ ನೈಜ-ಸಮಯದ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆಗಳ ವಿರುದ್ಧ ಈ ಅಂಶಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.',
  'yield_forecast': 'ಇಳುವರಿ ಅಂದಾಜು',
  'confidence': 'ಆತ್ಮವಿಶ್ವಾಸ',
  'core_factors': 'ಮುಖ್ಯ ಅಂಶಗಳು',
  'ai_strategy': 'AI ತಂತ್ರ',
  'onion': 'ಈರುಳ್ಳಿ',
  'tomato': 'ಟೊಮೇಟೊ',
  'potato': 'ಆಲೂಗಡ್ಡೆ',
  'rice': 'ಭತ್ತ',
  'wheat': 'ಗೋಧಿ',
  'maize': 'ಮೆಕ್ಕೆಜೋಳ',
  'cotton': 'ಹತ್ತಿ',
  'sugarcane': 'ಕಬ್ಬು',
  'clay_loam': 'ಜೇಡಿಮಣ್ಣು',
  'sandy_soil': 'ಮರಳು ಮಣ್ಣು',
  'sandy_loam': 'ಮರಳು ಮಿಶ್ರಿತ ಮಣ್ಣು',
  'red_loamy': 'ಕೆಂಪು ಮಣ್ಣು',
  'black_cotton': 'ಕಪ್ಪು ಹತ್ತಿ ಮಣ್ಣು',
  'silt_loam': 'ಹೂಳು ಮಿಶ್ರಿತ ಮಣ್ಣು',
  'peat': 'ಪೀಟ್ ಮಣ್ಣು',
  'chalky': 'ಚಾಕಿ ಮಣ್ಣು',
  'black_soil': 'ಕಪ್ಪು ಮಣ್ಣು',
  'red_soil': 'ಕೆಂಪು ಮಣ್ಣು',
  'acres': 'ಎಕರೆ',
  'select_language': 'ಬಾಷೆಯನ್ನು ಆರಿಸಿ',
  'language': 'ಭಾಷೆ',
  'yield_outlook': '7-ದಿನಗಳ ಇಳುವರಿ ದೃಷ್ಟಿಕೋನ',
  'good_potential': 'ಉತ್ತಮ ಸಾಮರ್ಥ್ಯ',
  'climatic_stress': 'ಹವಾಮಾನ ಒತ್ತಡ',
  'field_parameters': 'ಹೊಲದ ನಿಯತಾಂಕಗಳು',
  'system_health': 'ಸಿಸ್ಟಮ್ ಆರೋಗ್ಯ',
  'active_feed': 'ಸಕ್ರಿಯ ಫೀಡ್:',
  'api_stable': 'ಹವಾಮಾನ_ಎಪಿಐ_ಸ್ಥಿರ',
  'estimated_yield': 'ಅಂದಾಜು ಇಳುವರಿ',
  'low_reliability': 'ಕಡಿಮೆ ವಿಶ್ವಾಸಾರ್ಹತೆ',
  'medium_reliability': 'ಮಧ್ಯಮ ವಿಶ್ವಾಸಾರ್ಹತೆ',
  'high_reliability': 'ಹೆಚ್ಚಿನ ವಿಶ್ವಾಸಾರ್ಹತೆ',
  'yield_trajectory': '7-ದಿನಗಳ ಇಳುವರಿ ಪಥ',
  'contextual_insights': 'ಸಂದರ್ಭೋಚಿತ ಒಳನೋಟಗಳು',
  'temperature': 'ತಾಪಮಾನ',
  'soil_moisture': 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
  'disease_risk': 'ರೋಗದ ಅಪಾಯ',
  'sunlight': 'ಸೂರ್ಯನ ಬೆಳಕು',
  'optimal': 'ಅತ್ಯುತ್ತಮ',
  'monitor': 'ಮೇಲ್ವಿಚಾರಣೆ',
  'warning': 'ಎಚ್ಚರಿಕೆ',
  'good': 'ಉತ್ತಮ',
  'diffuse': 'ಪ್ರಸರಣ',
  'expected_harvest_date': 'ನಿರೀಕ್ಷಿತ ಸುಗ್ಗಿಯ ದಿನಾಂಕ',
  'run_prediction': 'ಮುನ್ಸೂಚನೆಯನ್ನು ಚಲಾಯಿಸಿ',
  'harvest_window_warning': 'ಸೂಚನೆ: ಸುಗ್ಗಿಯ ದಿನಾಂಕವು 14 ದಿನಗಳ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆಯ ವ್ಯಾಪ್ತಿ ಮೀರಿದೆ. AI ಕಾಲೋಚಿತ ಹವಾಮಾనాన్ని ಆಧರಿಸಿ ಊಹಿಸುತ್ತದೆ.',
  'financial_outlook': 'ಹಣಕಾಸಿನ ದೃಷ್ಟಿಕೋನ',
  'projected_revenue': 'ಯೋಜಿತ ಆದಾಯ',
  'estimated_cost': 'ಅಂದಾಜು ವೆಚ್ಚ',
  'net_profit': 'ನಿವ್ವಳ ಲಾಭ',
  'financial_disclaimer': '* {cropName} ಪ್ರಸ್ತುತ ಮಾರುಕಟ್ಟೆ ಸರಾಸರಿ ಆಧಾರಿತ ಅಂದಾಜುಗಳು. ನಿಜವಾದ ಆದಾಯ ಬದಲಾಗಬಹುದು.',
  'hello': 'ನಮಸ್ಕಾರ',
  'smart_tools': 'ಸ್ಮಾರ್ಟ್ ಸಾಧನಗಳು',
  'crop_doctor': 'ಬೆಳೆ ವೈದ್ಯರು',
  'crop_doctor_desc': 'AI ಸಸ್ಯ ರೋಗನಿರ್ಣಯ',
  'yield_est': 'ಇಳುವರಿ ಅಂದಾಜು',
  'yield_est_desc': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
  'market': 'ಮಾರುಕಟ್ಟೆ',
  'market_desc': 'ನೇರ ಬೆಲೆಗಳು',
  'ask_expert': 'ತಜ್ಞರನ್ನು ಕೇಳಿ',
  'ask_expert_desc': '24/7 ಕೃಷಿ ಮಾರ್ಗದರ್ಶನ',
  'rice_field': 'ಭತ್ತದ ಹೊಲ',
  'wheat_field': 'ಗೋಧಿ ಹೊಲ',
  'corn_field': 'ಜೋಳದ ಹೊಲ',
  'onion_field': 'ಈರುಳ್ಳಿ ಹೊಲ',
  'tomato_field': 'ಟೊಮೇಟೊ ಹೊಲ',
  'cotton_field': 'ಹತ್ತಿ ಹೊಲ',
  'sugarcane_field': 'ಕಬ್ಬಿನ ಹೊಲ',
  'vegetable_patch': 'ತರಕಾರಿ ತೋಟ',
  'custom_input': 'ಕಸ್ಟಮ್',
  'acreage_small': '< 1 ಎಕರೆ',
  'acreage_medium': '1-2 ಎಕರೆ',
  'acreage_large': '2-5 ಎಕರೆ',
  'acreage_very_large': '5-10 ಎಕರೆ',
  'acreage_estate': '> 10 ಎಕರೆ',
  'login_tagline': 'ನಿಮ್ಮ ಬುದ್ಧಿವಂತ ಕೃಷಿ ಸಹಾಯಕ',
  'login_title': 'ರೈತ ಲಾಗಿನ್',
  'login_otp_title': 'ಪರಿಶೀಲನೆ ಕೋಡ್ ನಮೂದಿಸಿ',
  'login_phone_label': 'ಫೋನ್ ಸಂಖ್ಯೆ',
  'login_phone_hint': '98765 43210',
  'login_send_otp': 'OTP ಕಳುಹಿಸಿ',
  'login_otp_sent_to': 'ಕಳುಹಿಸಲಾಗಿದೆ',
  'login_verify': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ',
  'login_change_number': 'ಸಂಖ್ಯೆ ಬದಲಾಯಿಸಿ',
  'login_powered_by': 'Gemini 3.0 ಸಹಾಯದಿಂದ',
  'upload_crop_image': 'ಬೆಳೆ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'take_photo_instruction': 'ಪೀಡಿತ ಪ್ರದೇಶದ ಸ್ಪಷ್ಟ ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
  'upload_image': 'ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  'supports_formats': 'ಬೆಂಬಲಿಸುತ್ತದೆ: JPG, PNG',
  'camera': 'ಕ್ಯಾಮರಾ',
  'gallery': 'ಗ್ಯಾಲರಿ',
  'analyze_crop': 'ಬೆಳೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
  'analyzing': 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
  'identifying_diseases': 'ರೋಗಗಳನ್ನು ಗುರುತಿಸಲಾಗುತ್ತಿದೆ',
  'diagnosis_results': 'ರೋಗನಿರ್ಣಯ ಫಲಿತಾಂಶಗಳು',
  'diagnosis_placeholder': 'ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ವಿಶ್ಲೇಷಿಸಿ',
  'detected_issue': 'ಪತ್ತೆಯಾದ समस्या',
  'healthy_plant': 'ಆರೋಗ್ಯಕರ ಸಸ್ಯ',
  'recommended_treatment': 'ಶಿಫಾರಸು ಮಾಡಿದ ಚಿಕಿತ್ಸೆ',
  'generate_report': 'ವರದಿ ರಚಿಸಿ',
  'listen_advice': 'ದ ಸಲಹೆಯನ್ನು ಕೇಳಿ',
  'playing_advice': 'ಸಲಹೆ ಪ್ಲೇ ಆಗುತ್ತಿದೆ...',
  'getting_audio': 'ಆಡಿಯೋ ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
  'describe_issue_hint': 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
  'climate_aware_forecasting': 'ಹವಾಮಾನ-ಜಾಗೃತ ಮುನ್ಸೂಚನೆ',
  'ai_engine_reasoning': 'ನಿಮ್ಮ ಹೊಲದ ವಿವರಗಳನ್ನು ಒದಗಿಸಿದ ನಂತರ, ನಮ್ಮ AI ಎಂಜಿನ್ ಜೆಮಿನಿ 3.0 ಪ್ರೊ ಈ ಕೆಳಗಿನವುಗಳ ಮೇಲೆ ಬಹು-ಅಂಶಗಳ ತರ್ಕವನ್ನು ನಡೆಸುತ್ತದೆ:',
  'reasoning_factor_1': 'ಸ್ಥಳೀಯ 7-ದಿನಗಳ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆಗಳು',
  'reasoning_factor_2': 'ಬೆಳೆ-ನಿರ್ದಿಷ್ಟ ಬೆಳವಣಿಗೆಯ ಚಕ್ರಗಳು',
  'reasoning_factor_3': 'ಮಣ್ಣಿನ ಉತ್ಪಾದಕತೆ ಮಾದರಿಗಳು',
  'reasoning_factor_4': 'ಪ್ರಾದೇಶಿಕ ಇತಿಹಾಸ',
  'challenge_diagnosis': 'ರೋಗನಿರ್ಣಯವನ್ನು ಸವಾಲು ಮಾಡಿ',
  'ai_reasoning': 'AI ಕಾರಣ',
  'soil_condition': 'ಮಣ್ಣಿನ ಸ್ಥಿತಿ',
  'weather_condition': 'ಹವಾಮಾನ ಸ್ಥಿತಿ',
  'missed_info_hint': 'ನಾನು ಏನನ್ನು ಕಳೆದುಕೊಂಡೆ?',
  'provide_feedback_error': 'ದಯವಿಟ್ಟು ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ.',
  'soil_normal': 'ಸಾಮಾನ್ಯ',
  'soil_dry': 'ಒಣ/ಮರಳು',
  'soil_wet': 'ತೇವ/ಜೇಡಿಮಣ್ಣು',
  'soil_log': 'ನೀರು ನಿಂತಿದೆ',
  'weather_sunny': 'ಬಿಸಿಲು',
  'weather_cloudy': 'ಮೋಡ',
  'weather_rain': 'ಭಾರೀ ಮಳೆ',
  'weather_windy': 'ಗಾಳಿ',
  'refining': 'ಪರಿಷ್ಕರಿಸಲಾಗುತ್ತಿದೆ...',
  'ask_second_opinion': 'ಎರಡನೇ ಅಭಿಪ್ರಾಯ ಕೇಳಿ',
  'select_harvest_date': 'ದಯವಿಟ್ಟು ಮೊದಲು ಅಂದಾಜು ಸುಗ್ಗಿಯ ದಿನಾಂಕವನ್ನು ಆರಿಸಿ.',
  'prediction_failed': 'ಮುನ್ಸೂಚನೆ ವಿಫಲವಾಗಿದೆ',
  'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  'soil_and_environment': 'ಮಣ್ಣು ಮತ್ತು ಪರಿಸರ',
  'help_gemini_understand': 'ನಿಮ್ಮ ಭೂಮಿಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಜೆಮಿನಿಗೆ ಸಹಾಯ ಮಾಡಿ.',
  'select_soil_texture': 'ಮಣ್ಣಿನ ವಿನ್ಯಾಸವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  'irrigation_method': 'ನೀರಾವರಿ ವಿಧಾನ',
  'how_do_you_water': 'ನಿಮ್ಮ ಬೆಳೆಗಳಿಗೆ ನೀವು ಹೇಗೆ ನೀರು ಹಾಕುತ್ತೀರಿ?',
  'welcome_agripulse': 'AgriPulse ಗೆ ಸುಸ್ವಾಗತ',
  'setup_first_plot': 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ AI ಸಲಹೆಯನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಮೊದಲ ಫಾರ್ಮ್ ಪ್ಲಾಟ್ ಅನ್ನು ಹೊಂದಿಸಿ.',
  'plot_name': 'ಪ್ಲಾಟ್ ಹೆಸರು',
  'approx_acreage': 'ಅಂದಾಜು ಎಕರೆ',
  'continue': 'ಮುಂದುವರಿಸಿ',
  'finish_setup': 'ಸೆಟಪ್ ಮುಗಿಸಿ',
  'my_first_plot': 'ನನ್ನ ಮೊದಲ ಪ್ಲಾಟ್',
  'register_new_plot': 'ಹೊಸ ಪ್ಲಾಟ್ ಅನ್ನು ನೋಂದಾಯಿಸಿ',
  'plot_info': 'ಪ್ಲಾಟ್ ಮಾಹಿತಿ',
  'ground_advice_hint': 'ಪ್ಲಾಟ್ ವಿವರಗಳನ್ನು ನೀಡುವ ಮೂಲಕ AgriPulse ಗೆ ಅದರ ಸಲಹೆಯನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡಿ.',
  'submit_registration': 'ನೋಂದಣಿ ಸಲ್ಲಿಸಿ',
  'drip': 'ಹನಿ ನೀರಾವರಿ',
  'sprinkler': 'ತುಂತುರು ನೀರಾವರಿ',
  'manual_bucket': 'ಕೈಯಿಂದ / ಬಕೆಟ್ ಮೂಲಕ',
  'flood': 'ಕಾಲುವೆ ನೀರಾವರಿ',
  'rain_fed': 'ಮಳೆ ಆಧಾರಿತ',
  'clay_loam_desc': 'ಅತ್ಯುತ್ತಮ ನೀರು ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುವ ಸಾಮರ್ಥ್ಯ, ಹೆಚ್ಚಿನ ಪೋಷಕಾಂಶಗಳು.',
  'sandy_soil_desc': 'ವೇಗದ ಒಳಚರಂಡಿ, ಆಗಾಗ್ಗೆ ನೀರಾವರಿ ಅಗತ್ಯವಿರುತ್ತದೆ.',
  'red_loamy_desc': 'ಸಮತೋಲಿತ ಒಳಚರಂಡಿ, ಹೆಚ್ಚಿನ ಬೆಳೆಗಳಿಗೆ ಉತ್ತಮವಾಗಿದೆ.',
  'black_cotton_desc': 'ಹೆಚ್ಚಿನ ತೇವಾಂಶ ಸಾಮರ್ಥ್ಯ, ಹತ್ತಿ/ಈರುಳ್ಳಿಗೆ ಸೂಕ್ತವಾಗಿದೆ.',
  'recent_activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
  'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
  'error_loading_activity': 'ಚಟುವಟಿಕೆಯನ್ನು ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ',
  'move_to_plot': 'ಪ್ಲಾಟ್‌ಗೆ ಸರಿಸಿ',
  'no_activity_yet': 'ಇನ್ನೂ ಯಾವುದೇ ಚಟುವಟಿಕೆ ಇಲ್ಲ',
  'start_scan_prediction_hint': 'ಇತಿಹಾಸವನ್ನು ನೋಡಲು ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಅಥವಾ ಇಳುವರಿ ಮುನ್ಸೂಚನೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ',
  'move_record_to_plot': 'ದಾಖಲೆಯನ್ನು ಪ್ಲಾಟ್‌ಗೆ ಸರಿಸಿ',
  'select_destination_plot': 'ಈ ಚಟುವಟಿಕೆಗಾಗಿ ಯೋಜಿತ ಪ್ಲಾಟ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
  'moved_successfully': 'ಯಶಸ್ವಿಯಾಗಿ ಸರಿಸಲಾಗಿದೆ!',
  'today': 'ಇಂದು',
  'yesterday': 'ನಿನ್ನೆ',
  'm_ago': 'ನಿಮಿಷದ ಹಿಂದೆ',
  'h_ago': 'ಗಂಟೆಯ ಹಿಂದೆ',
  // Field Selector
  'select_plot': 'ಪ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ',
  'switch_plot_hint': 'ಪ್ಲಾಟ್ ಬದಲಾಯಿಸಲು ಸ್ಪರ್ಶಿಸಿ',
  'select_farming_plot': 'ಹೊಲದ ಪ್ಲಾಟ್ ಆಯ್ಕೆಮಾಡಿ',
  'plot_environment_hint': 'AgriPulse ಎಲ್ಲಾ AI ಸಲಹೆಗಳನ್ನು ಆಯ್ದ ಪ್ಲಾಟ್ ಪರಿಸರಕ್ಕೆ ಅನುಗುಣವಾಗಿ ನೀಡುತ್ತದೆ.',
  'main_plot_north': 'ಮುಖ್ಯ ಪ್ಲಾಟ್ (ಉತ್ತರ)',
  'unassigned_legacy_data': 'ಸಾಮಾನ್ಯ ವಿಚಾರಣೆ',
  'unknown_crop': 'ಅಜ್ಞಾತ ಬೆಳೆ',
  'mixed_soil': 'ಮಿಶ್ರ ಮಣ್ಣು',
  'activity_log': 'ಚಟುವಟಿಕೆ ದಾಖಲೆ',
  'search_history_hint': 'ಇತಿಹಾಸವನ್ನು ಹುಡುಕಿ...',
  'detailed_report': 'ವಿವರವಾದ ವರದಿ',
  'select_record_detail': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ದಾಖಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  'detailed_data_unavailable': 'ಈ ಐತಿಹಾಸಿಕ ದಾಖಲೆಗಾಗಿ ವಿವರವಾದ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
  'run_new_prediction_hint': 'ಪೂರ್ಣ ವಿವರಗಳನ್ನು ನೋಡಲು ದಯವಿಟ್ಟು ಹೊಸ ಮುನ್ಸೂಚನೆಯನ್ನು ಚಲಾಯಿಸಿ.',
  'health_status': 'ಆರೋಗ್ಯ ಸ್ಥಿತಿ',
  'diagnosis_analysis': 'ರೋಗನಿರ್ಣಯ ವಿಶ್ಲೇಷಣೆ',
  'severity_score': 'ಗಂಭೀರತೆಯ ಸ್ಕೋರ್',
  'severity_high': 'ಹೆಚ್ಚು',
  'severity_medium': 'ಮಧ್ಯಮ',
  'severity_low': 'ಕಡಿಮೆ',
  'environmental_status': 'ಪರಿಸರ ಸ್ಥಿತಿ',
  'confidence_metrics': 'ಆತ್ಮವಿಶ್ವಾಸ ಮಾಪನಗಳು',
  'ai_recommendation': 'AI ಶಿಫಾರಸು',
  'soil_correction': 'ಮಣ್ಣು ತಿದ್ದುಪಡಿ',
  'model_precision': 'ಮಾದರಿ ನಿಖರತೆ',
  'verified_ai': 'AgriPulse AI ನಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
  'findings': 'ರೋಗನಿರ್ಣಯದ ಆವಿಷ್ಕಾರಗಳು',
  'confidence_score_cap': 'ಆತ್ಮವಿಶ್ವಾಸ ಸ್ಕೋರ್',
  'qtl_acre': 'ಕ್ವಿಂ/ಎಕರೆ',
  'clear_history': 'ಇತಿಹಾಸವನ್ನು ತೆರವುಗೊಳಿಸಿ',
  'clear_history_confirm': 'ನೀವ ಖಂಡಿತವಾಗಿಯೂ ಎಲ್ಲಾ ಇತಿಹಾಸವನ್ನು ತೆರವುಗೊಳಿಸಲು ಬಯಸುತ್ತೀರಾ?',
  'delete_plot': 'ಜಮೀನನ್ನು ಅಳಿಸಿ',
  'delete_plot_confirm': 'ನೀವು ಈ ಜಮೀನನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುತ್ತೀರಾ?',
  'clear': 'ತೆರವುಗೊಳಿಸಿ',
  'cancel': 'ರದ್ದುಮಾಡಿ',
  'market_insights': 'ಮಾರುಕಟ್ಟೆ ಒളನೋಟಗಳು',
  'treatment_plan': 'ಚಿಕಿತ್ಸಾ ಯೋಜನೆ',
  'humidity': 'ಆರ್ದ್ರತೆ',
  'confidence_level': 'ಆತ್ಮವಿಶ್ವಾಸ ಮಟ್ಟ',
  'jan': 'ಜನವರಿ',
  'feb': 'ಫೆಬ್ರವರಿ',
  'mar': 'ಮಾರ್ಚ್',
  'apr': 'ಏಪ್ರಿಲ್',
  'may': 'ಮೇ',
  'jun': 'ಜೂನ್',
  'jul': 'ಜುಲೈ',
  'aug': 'ಆಗಸ್ಟ್',
  'sep': 'ಸೆಪ್ಟೆಂಬರ್',
  'oct': 'ಅಕ್ಟೋಬರ್',
  'nov': 'ನವೆಂಬರ್',
  'dec': 'ಡಿಸೆಂಬರ್',
  'analysis_failed_connection': 'ವಿಶ್ಲೇಷಣೆ ವಿಫಲವಾಗಿದೆ. ಸಂಪರ್ಕ ದೋಷ.',
  'refinement_failed': 'ಪರಿಷ್ಕರಣೆ ವಿಫಲವಾಗಿದೆ',
  'audio_empty_error': 'ಸರ್ವರ್‌ನಿಂದ ಖಾലി ಆಡಿಯೋ ಸ್ವೀಕರಿಸಲಾಗಿದೆ.',
  'audio_play_failed': 'ಸಲಹೆ ಪ್ಲೇ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ',
  'unknown_issue': 'ಅಪರಿಚಿತ ಸಮಸ್ಯೆ',
  'consult_expert': 'ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
  'no_advice_available': 'ಯಾವುದೇ ಸಲಹೆ ಲಭ್ಯವಿಲ್ಲ.',
  'diagnosis_prefix': 'ರೋಗನಿರ್ಣಯ',
  'recommendation_prefix': 'ಶಿಫಾರಸು',
  'scan_in': 'ಸ್ಕ್ಯಾನ್:',
  'irrigation_stage': 'ನೀರ್ಪಾವನ ಹಂತ',
  'weather_events': 'ಹವಾಮಾನ ಘಟನೆಗಳು',
  'spread_pattern': 'ಹರಡುವಿಕೆ ಮಾದರಿ',
  'intervention_log': 'ಹಸ್ತಕ್ಷೇಪ ಲಾಗ್',
  'establishment': 'ಸ್ಥಾಪನೆ',
  'sprouting': 'ಮೊಳಕೆ',
  'leaf_dev': 'ಎಲೆ ಅಭಿವೃದ್ಧಿ',
  'bulb_init': 'ಗೆಡ್ಡೆ ಪ್ರಾರಂಭ',
  'bulb_dev': 'ಗೆಡ್ಡೆ ಅಭಿವೃದ್ಧಿ',
  'bone_dry': 'ಬಹಳ ಒಣಗಿದ',
  'moist': 'ತೇವಾಂಶವುಳ್ಳ',
  'waterlogged': 'ನೀರು ನಿಂತಿರುವ',
  'frost': 'ಹಿಮ',
  'heavy_rain': 'ಭಾರಿ ಮಳೆ',
  'drizzle': 'ಜಿನುಗು ಮಳೆ',
  'wind': 'ಗಾಳಿ',
  'too_hot': 'ಬಹಳ ಬಿಸಿ',
  'isolated': 'ಪ್ರತ್ಯೇಕವಾದ',
  'localized': 'ಸ್ಥಳೀಯ',
  'field_wide': 'ಕ್ಷೇತ್ರದಾದ್ಯಂತ',
  'last_treatment': 'ಕೊನೆಯದಾಗಿ ಅನ್ವಯಿಸಿದ್ದು',
  'dosage': 'ಡೋಸೇಜ್',
  'fert_organic': 'ಸಾವಯವ',
  'fert_npk': 'NPK',
  'fungicide': 'ಶಿಲೀಂಧ್ರನಾಶಕ',
  'insecticide': 'ಕೀಟನಾಶಕ',
  'low': 'ಕಡಿಮೆ',
  'medium': 'ಮಧ್ಯಮ',
  'high': 'ಹೆಚ್ಚು',
  'workspace_context': 'ಕ್ಷೇತ್ರದ ಸನ್ನಿವೇಶ',
  'leaf_texture': 'ಎಲೆಯ ವಿನ್ಯಾಸ',
  'texture_brittle': 'ಸುಲಭವಾಗಿ ಪುಡಿಯಾಗುವ',
  'texture_slimy': 'ಲಸಲಸೆಯಾದ',
  'texture_rubbery': 'ರಬ್ಬರ್‌ನಂತಹ',
  'odor_presence': 'ವಾಸನೆಯ ಉಪಸ್ಥಿತಿ',
  'odor_foul': 'ದುರ್ವಾಸನೆ',
  'odor_none': 'ವಾಸನೆ ಇಲ್ಲ',
  'speed_of_spread': 'ಹರಡುವ ವೇಗ',
  'spread_overnight': 'ರಾತ್ರೋರಾತ್ರಿ ಕಾಣಿಸಿಕೊಂಡಿದೆ',
  'spread_slow': 'ನಿಧಾನವಾಗಿ ಹರಡುತ್ತಿದೆ',
  'role_user': 'ನೀವು',
  'role_ai': 'AgriPulse AI',
  'analysis_complete': 'ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ',
  'default_ai_response': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯ ಆಧಾರದ ಮೇಲೆ ನವೀಕರಿಸಿದ ರೋಗನಿರ್ಣಯ.',
  'treatment_adjustment_label': 'ಹೊಂದಾಣಿಕೆ',
  'sidebar_waiting_hint': 'ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ... AI ರೋಗನಿರ್ಣಯವು ಕಾಣಿಸಿಕೊಂಡ ನಂತರ ಅದನ್ನು ಸುಧಾರಿಸಲು ಈ ವಿಭಾಗವನ್ನು ಬಳಸಿ.',
  'view_report': 'ವರದಿ ವೀಕ್ಷಿಸಿ',
  'initial_request': 'ಆರಂಭಿಕ ವಿನಂತಿ',
  'initial_diagnosis': 'ಆರಂಭಿಕ ರೋಗನಿರ್ಣಯ',
  'refined_diagnosis': 'ಸುಧಾರಿತ ರೋಗನಿರ್ಣಯ',
  'refinement_reasoning': 'ಸುಧಾರಣೆಯ ತರ್ಕ',
  'refinement_feedback': 'ಸುಧಾರಣೆಯ ಪ್ರತಿಕ್ರಿಯೆ',
  'ai_findings': 'AI ಸಂಶೋಧನೆಗಳು',
  'adjusted_treatment_plan': 'ಹೊಂದಾಣಿಕೆ ಮಾಡಲಾದ ಚಿಕಿತ್ಸಾ ಯೋಜನೆ',
  'view_standard_treatment': 'ಪ್ರಮಾಣಿತ ಚಿಕಿತ್ಸೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
  'view_adjusted_plan': 'ಹೊಂದಾಣಿಕೆಯ ಯೋಜನೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
  'delete': 'ಅಳಿಸಿ',
  'delete_record_confirm': 'ಈ ದಾಖಲೆಯನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿರುವಿರಾ?',
  'record_deleted': 'ದಾಖಲೆಯನ್ನು ಅಳಿಸಲಾಗಿದೆ',
  'prediction': 'ಮುನ್ಸೂಚನೆ',
  'forecast': 'ಭವಿಷ್ಯವಾಣಿ',
};
