const Map<String, String> malayalamTranslations = {
  'yield_prediction': 'വിളവ് പ്രവചനം',
  'predict_harvest': 'നിങ്ങളുടെ വിളവെടുപ്പ് പ്രവചിക്കുക',
  'enter_details': 'AI-അധിഷ്ഠിത വിളവ് അന്ദാജിനായി നിങ്ങളുടെ കൃഷിയിട വിവരങ്ങൾ നൽകുക.',
  'crop_details': 'വിള വിവരങ്ങൾ',
  'field_name': 'കൃഷിയിടത്തിൻ്റെ പേര്',
  'crop_name': 'വിളയുടെ പേര്',
  'field_area': 'കൃഷിയിട വിസ്തൃതി (ഏക്കർ)',
  'environment': 'പരിസ്ഥിതി',
  'soil_type': 'മണ്ണ് ഇനം',
  'planted_date': 'നട്ട തീയതി',
  'get_prediction': 'പ്രവചനം നേടുക',
  'gemini_hint': 'ജെമിനി 3.0 പ്രോ തത്സമയ കാലാവസ്ഥാ പ്രവചനങ്ങളുമായി ഈ ഘടകങ്ങളെ വിശകലനം ചെയ്യും.',
  'yield_forecast': 'വിളവ് പ്രവചനം',
  'confidence': 'വിശ്വാസ്യത',
  'core_factors': 'പ്രധാന ഘടകങ്ങൾ',
  'ai_strategy': 'AI തന്ത്രം',
  'onion': 'സവാള',
  'tomato': 'തക്കാളി',
  'potato': 'ഉരുളക്കിഴങ്ങ്',
  'rice': 'നെല്ല്',
  'wheat': 'ഗോതമ്പ്',
  'maize': 'ചോളം',
  'cotton': 'പരുത്തി',
  'sugarcane': 'കരിമ്പ്',
  'clay_loam': 'കളിമണ്ണ്',
  'sandy_soil': 'മണൽ മണ്ണ്',
  'sandy_loam': 'മണൽ കലർന്ന മണ്ണ്',
  'red_loamy': 'ചുവന്ന മണ്ണ്',
  'black_cotton': 'കറുത്ത പരുത്തി മണ്ണ്',
  'silt_loam': 'എക്കൽ മണ്ണ്',
  'peat': 'പീറ്റ് മണ്ണ്',
  'chalky': 'ചുണ്ണാമ്പ് മണ്ണ്',
  'black_soil': 'കരിമണ്ണ്',
  'red_soil': 'ചെമ്മണ്ണ്',
  'acres': 'ഏക്കർ',
  'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
  'language': 'ഭാഷ',
  'yield_outlook': '7 ദിവസത്തെ വിളവ് അവലോകനം',
  'good_potential': 'മികച്ച വിളവ് സാധ്യത',
  'climatic_stress': 'കാലാവസ്ഥാ സമ്മർദ്ദം',
  'field_parameters': 'കൃഷിയിട പാരാമീറ്ററുകൾ',
  'system_health': 'സിസ്റ്റം ആരോഗ്യം',
  'active_feed': 'സജീവ ഫീഡ്:',
  'api_stable': 'കാലാവസ്ഥ_API_സ്ഥിരമാണ്',
  'estimated_yield': 'പ്രതീക്ഷിക്കുന്ന വിളവ്',
  'low_reliability': 'കുറഞ്ഞ വിശ്വാസ്യത',
  'medium_reliability': 'മിതമായ വിശ്വാസ്യത',
  'high_reliability': 'ഉയർന്ന വിശ്വാസ്യത',
  'yield_trajectory': '7 ദിവസത്തെ വിളവ് പാത',
  'contextual_insights': 'സാഹചര്യപരമായ ഉൾക്കാഴ്ചകൾ',
  'temperature': 'താപനില',
  'soil_moisture': 'മണ്ണിലെ ഈർപ്പം',
  'disease_risk': 'രോഗസാധ്യത',
  'sunlight': 'സൂര്യപ്രകാശം',
  'optimal': 'അത്യുത്തമം',
  'monitor': 'നിരീക്ഷിക്കുക',
  'warning': 'മുന്നറിയിപ്പ്',
  'good': 'നല്ലത്',
  'diffuse': 'വ്യാപിച്ച',
  'expected_harvest_date': 'പ്രതീക്ഷിക്കുന്ന വിളവെടുപ്പ് തീയതി',
  'run_prediction': 'പ്രവചനം നടത്തുക',
  'harvest_window_warning': 'ശ്രദ്ധിക്കുക: വിളവെടുപ്പ് തീയതി 14 ദിവസത്തെ കാലാവസ്ഥാ പ്രവചന പരിധിക്ക് അപ്പുറമാണ്. AI സീസണൽ കാലാവസ്ഥാ ശരാശരി ഉപയോഗിക്കും.',
  'financial_outlook': 'സാമ്പത്തിക അവലോകനം',
  'projected_revenue': 'പ്രതീക്ഷിക്കുന്ന വരുമാനം',
  'estimated_cost': 'കണക്കാക്കിയ ചെലവ്',
  'net_profit': 'അറ്റാദായം',
  'financial_disclaimer': '* {cropName} നിലവിലെ വിപണി ശരാശരി അടിസ്ഥാനമാക്കിയുള്ള കണക്കുകൾ. യഥാർത്ഥ വരുമാനം വ്യത്യാസപ്പെടാം.',
  'hello': 'നമസ്കാരം',
  'smart_tools': 'സ്മാർട്ട് ഉപകരണങ്ങൾ',
  'crop_doctor': 'വിള ഡോക്ടർ',
  'crop_doctor_desc': 'AI സസ്യ രോഗനിർണയം',
  'yield_est': 'വിളവ് എസ്റ്റി.',
  'yield_est_desc': 'കാലാവസ്ഥാ പ്രവചനം',
  'market': 'മാർക്കറ്റ്',
  'market_desc': 'ലൈവ് വിലകളും ട്രെൻഡുകളും',
  'ask_expert': 'വിദഗ്ധനോട് ചോദിക്കുക',
  'ask_expert_desc': '24/7 കാർഷിക മാർഗനിർദേശം',
  
  // Coming Soon Features
  'coming_soon': 'ഉടൻ വരുന്നു',
  'soil_health_time_machine': 'മണ്ണ് ആരോഗ്യ ടൈം-മെഷീൻ',
  'soil_health_desc': 'മണ്ണിലെ മാറ്റങ്ങൾ ട്രാക്ക് ചെയ്യുക',
  'market_analysis': 'വിപണി വിശകലനം',
  'market_analysis_desc': 'വിള വില പ്രവണതകൾ',
  'smart_irrigation': 'സ്മാർട്ട് ജലസേചന ഷെഡ്യൂളർ',
  'smart_irrigation_desc': 'AI ജല ഒപ്റ്റിമൈസേഷൻ',
  'voice_command': 'വോയ്സ്-ഒൺലി കമാൻഡ് സെന്റർ',
  'voice_command_desc': 'കൈകൾ സ്വതന്ത്രമായ പ്രവർത്തനം',
  'support_24_7': '24/7 പിന്തുണ',
  'support_24_7_desc': 'തൽക്ഷണ വിദഗ്ധ സഹായം',
  'sustainable_farming': 'സുസ്ഥിര കൃഷി',
  'sustainable_farming_desc': 'പരിസ്ഥിതി സൗഹൃദ രീതികൾ',
  'community_alert': 'കമ്മ്യൂണിറ്റി അലേർട്ട്',
  'community_alert_desc': 'പ്രാദേശിക കീട മുന്നറിയിപ്പുകൾ',
  'government_schemes': 'സർക്കാർ പദ്ധതികൾ',
  'government_schemes_desc': 'സബ്സിഡികളും ആനുകൂല്യങ്ങളും',
  'onboarding_tutorials': 'ഓൺബോർഡിംഗ് ട്യൂട്ടോറിയലുകൾ',
  'onboarding_tutorials_desc': 'ഘട്ടം ഘട്ടമായുള്ള ഗൈഡുകൾ',
   
  'rice_field': 'നെൽവയൽ',
  'wheat_field': 'ഗോതമ്പ് വയൽ',
  'corn_field': 'ധാന്യം വയൽ',
  'onion_field': 'ഉള്ളി വയൽ',
  'tomato_field': 'തക്കാളി വയൽ',
  'cotton_field': 'പരുത്തി വയൽ',
  'sugarcane_field': 'കരിമ്പ് വയൽ',
  'vegetable_patch': 'പച്ചക്കറി തോട്ടം',
  'custom_input': 'കസ്റ്റം',
  'acreage_small': '< 1 ഏക്കർ',
  'acreage_medium': '1-2 ഏക്കർ',
  'acreage_large': '2-5 ഏക്കർ',
  'acreage_very_large': '5-10 ഏക്കർ',
  'acreage_estate': '> 10 ഏക്കർ',
  'login_skip_demo': 'ലോഗിൻ വേണ്ട (ഡെമോ)',
  'login_tagline': 'നിങ്ങളുടെ ബുദ്ധിമാനായ കൃഷി കൂട്ടാളി',
  'login_title': 'കർഷക ലോഗിൻ',
  'login_otp_title': 'സ്ഥിരീകരണ കോഡ് നൽകുക',
  'login_phone_label': 'ഫോൺ നമ്പർ',
  'login_phone_hint': '98765 43210',
  'login_send_otp': 'OTP അയയ്ക്കുക',
  'login_otp_sent_to': 'അയച്ചത്',
  'login_verify': 'പരിശോധിച്ച് ലോഗിൻ ചെയ്യുക',
  'login_change_number': 'നമ്പർ മാറ്റുക',
  'login_powered_by': 'Gemini 3.0 നൽകുന്നു',
  'upload_crop_image': 'വിളയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
  'take_photo_instruction': 'ബാധിച്ച പ്രദേശത്തിന്റെ വ്യക്തമായ ഫോട്ടോ എടുക്കുക',
  'upload_image': 'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
  'supports_formats': 'പിന്തുണയ്ക്കുന്നു: JPG, PNG',
  'camera': 'ക്യാമറ',
  'gallery': 'ഗാലറി',
  'analyze_crop': 'വിള വിശകലനം ചെയ്യുക',
  'analyzing': 'വിശ്കലനം ചെയ്യുന്നു...',
  'identifying_diseases': 'രോഗങ്ങളെ തിരിച്ചറിയുന്നു',
  'diagnosis_results': 'രോഗനിർണയ ഫലങ്ങൾ',
  'diagnosis_placeholder': 'ചിത്രം അപ്‌ലോഡ് ചെയ്ത് വിശകലനം ചെയ്യുക',
  'detected_issue': 'കണ്ടെത്തിയ പ്രശ്നം',
  'healthy_plant': 'ആരോഗ്യമുള്ള ചെടി',
  'recommended_treatment': 'നിർദ്ദേശിച്ച ചികിത്സ',
  'generate_report': 'റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
  'listen_advice': 'ഉപദേശം കേൾക്കുക',
  'playing_advice': 'ഉപദേശം കേൾപ്പിക്കുന്നു...',
  'getting_audio': 'ഓഡിയോ എടുക്കുന്നു...',
  'describe_issue_hint': 'പ്രശ്നം വിവരിക്കുക',
  'climate_aware_forecasting': 'കാലാവസ്ഥാ അധിഷ്ഠിത പ്രവചനം',
  'ai_engine_reasoning': 'നിങ്ങളുടെ കൃഷിയിട വിവരങ്ങൾ നൽകിക്കഴിഞ്ഞാൽ, ഞങ്ങളുടെ AI എഞ്ചിൻ ജെമിനി 3.0 പ്രോ ഇനിപ്പറയുന്നവയിൽ വിശകലനം നടത്തുന്നു:',
  'reasoning_factor_1': 'പ്രാദേശിക 7-ദിവസത്തെ കാലാവസ്ഥാ പ്രവചനങ്ങൾ',
  'reasoning_factor_2': 'വിളകളുടെ വളർച്ചാ ഘട്ടങ്ങൾ',
  'reasoning_factor_3': 'മണ്ണിലെ ഉൽപ്പാദനക്ഷമത മോഡലുകൾ',
  'reasoning_factor_4': 'പ്രാദേശിക ചരിത്രം',
  'challenge_diagnosis': 'രോഗനിർണയത്തെ വെല്ലുവിളിക്കുക',
  'ai_reasoning': 'AI യുക്തി',
  'soil_condition': 'മണ്ണിന്റെ അവസ്ഥ',
  'weather_condition': 'കാലാവസ്ഥ',
  'missed_info_hint': 'എന്താണ് വിട്ടുപോയത്?',
  'provide_feedback_error': 'ദയവായി അഭിപ്രായം നൽകുക.',
  'soil_normal': 'സാധാരണ',
  'soil_dry': 'വരണ്ട/മണൽ',
  'soil_wet': 'നനഞ്ഞ/കളിമണ്ണ്',
  'soil_log': 'വെള്ളക്കെട്ട്',
  'weather_sunny': 'വെയിൽ',
  'weather_cloudy': 'മേഘാവൃതമായ',
  'weather_rain': 'കനത്ത മഴ',
  'weather_windy': 'കാറ്റുള്ള',
  'refining': 'ശുദ്ധീകരിക്കുന്നു...',
  'ask_second_opinion': 'രണ്ടാമത്തെ അഭിപ്രായം ചോദിക്കുക',
  'select_harvest_date': 'ദയവായി ആദ്യം വിളവെടുപ്പ് തീയതി തിരഞ്ഞെടുക്കുക.',
  'prediction_failed': 'പ്രവചനം പരാജയപ്പെട്ടു',
  'retry': 'വീണ്ടും ശ്രമിക്കുക',
  'soil_and_environment': 'മണ്ണും പരിസ്ഥിതിയും',
  'help_gemini_understand': 'നിങ്ങളുടെ കൃഷിയിടം മനസ്സിലാക്കാൻ ജെമിനിയെ സഹായിക്കൂ.',
  'select_soil_texture': 'മണ്ണിന്റെ തരം തിരഞ്ഞെടുക്കുക',
  'irrigation_method': 'ജലസേചന രീതി',
  'how_do_you_water': 'നിങ്ങൾ എങ്ങനെയാണ് വിളകൾക്ക് നനയ്ക്കുന്നത്?',
  'welcome_agripulse': 'AgriPulse-ലേക്ക് സ്വാഗതം',
  'setup_first_plot': 'വ്യക്തിഗതമാക്കിയ AI ഉപദേശം ലഭിക്കുന്നതിന് നിങ്ങളുടെ ആദ്യത്തെ ഫാം പ്ലോട്ട് സജ്ജീകരിക്കുക.',
  'plot_name': 'പ്ലോട്ടിന്റെ പേര്',
  'approx_acreage': 'ഏകദേശ ഏക്കർ',
  'continue': 'തുടരുക',
  'finish_setup': 'സെറ്റപ്പ് പൂർത്തിയാക്കുക',
  'my_first_plot': 'എന്റെ ആദ്യ പ്ലോട്ട്',
  'register_new_plot': 'പുതിയ പ്ലോട്ട് രജിസ്റ്റർ ചെയ്യുക',
  'plot_info': 'പ്ലോട്ട് വിവരങ്ങൾ',
  'ground_advice_hint': 'പ്ലോട്ട് വിവരങ്ങൾ നൽകിക്കൊണ്ട് AgriPulse-നെ അതിന്റെ ഉപദേശങ്ങൾ മെച്ചപ്പെടുത്താൻ സഹായിക്കൂ.',
  'submit_registration': 'രജിസ്ട്രേഷൻ സമർപ്പിക്കുക',
  'drip': 'തുള്ളിനന',
  'sprinkler': 'സ്പ്രിംഗ്ലർ',
  'manual_bucket': 'മാനുവൽ / ബക്കറ്റ് വഴി',
  'flood': 'പ്രവാഹ ജലസേചനം',
  'rain_fed': 'മഴയെ ആശ്രയിച്ചുള്ളത്',
  'clay_loam_desc': 'മികച്ച ജലം സംഭരിക്കാനുള്ള കഴിവ്, ഉയർന്ന പോഷകങ്ങൾ.',
  'sandy_soil_desc': 'വേഗത്തിലുള്ള ഡ്രെയിനേജ്, ഇടയ്ക്കിടെ നനയ്ക്കേണ്ടതുണ്ട്.',
  'red_loamy_desc': 'സന്തുലിതമായ ഡ്രെയിനേജ്, മിക്ക വിളകൾക്കും അനുയോജ്യം.',
  'black_cotton_desc': 'ഉയർന്ന ഈർപ്പം നിലനിർത്താനുള്ള കഴിവ്, പരുത്തി/സവാള കൃഷിക്ക് അനുയോജ്യം.',
  'recent_activity': 'സമീപകാല പ്രവർത്തനങ്ങൾ',
  'see_all': 'എല്ലാം കാണുക',
  'error_loading_activity': 'പ്രവർത്തനങ്ങൾ ലോഡ് ചെയ്യുന്നതിൽ പിശക്',
  'move_to_plot': 'ഒരു പ്ലോട്ടിലേക്ക് മാറ്റുക',
  'no_activity_yet': 'ഇതുവരെ പ്രവർത്തനങ്ങളൊന്നുമില്ല',
  'start_scan_prediction_hint': 'ചരിത്രം കാണുന്നതിന് ഒരു വിള സ്കാൻ അല്ലെങ്കിൽ വിളവ് പ്രവചനം ആരംഭിക്കുക',
  'move_record_to_plot': 'റെക്കോർഡ് പ്ലോട്ടിലേക്ക് മാറ്റുക',
  'select_destination_plot': 'ഈ പ്രവർത്തനത്തിനായി ലക്ഷ്യസ്ഥാനം തിരഞ്ഞെടുക്കുക.',
  'moved_successfully': 'വിജയകരമായി മാറ്റി!',
  'today': 'ഇന്ന്',
  'tomorrow': 'നാളെ',
  'yesterday': 'ഇന്നലെ',
  'm_ago': 'മിനിറ്റ് മുമ്പ്',
  'h_ago': 'മണിക്കൂർ മുമ്പ്',
  // Field Selector
  'select_plot': 'പ്ലോട്ട് തിരഞ്ഞെടുക്കുക',
  'switch_plot_hint': 'പ്ലോട്ട് മാറ്റാൻ സ്പർശിക്കുക',
  'select_farming_plot': 'കൃഷി പ്ലോട്ട് തിരഞ്ഞെടുക്കുക',
  'plot_environment_hint': 'AgriPulse എല്ലാ AI ഉപദേശങ്ങളും തിരഞ്ഞെടുത്ത പ്ലോട്ട് പരിസ്ഥിതിക്ക് അനുസൃതമായി നൽകും.',
  'main_plot_north': 'പ്രധാന പ്ലോട്ട് (വടക്ക്)',
  'unassigned_legacy_data': 'പൊതു അന്വേഷണം',
  'unknown_crop': 'അജ്ഞാത വിള',
  'mixed_soil': 'മിശ്രിത മണ്ണ്',
  'activity_log': 'പ്രവർത്തന ലോഗ്',
  'search_history_hint': 'ചരിത്രം തിരയുക...',
  'detailed_report': 'വിശദമായ റിപ്പോർട്ട്',
  'select_record_detail': 'വിശദാംശങ്ങൾ കാണാൻ ഒരു റെക്കോർഡ് തിരഞ്ഞെടുക്കുക',
  'detailed_data_unavailable': 'ഈ ചരിത്ര റെക്കോർഡിനായി വിശദമായ വിവരങ്ങൾ ലഭ്യമല്ല.',
  'run_new_prediction_hint': 'പൂർണ്ണ വിവരങ്ങൾ കാണാൻ പുതിയ പ്രവചനം നടത്തുക.',
  'health_status': 'ആരോഗ്യ നില',
  'diagnosis_analysis': 'രോഗനിർണയ വിശകലനം',
  'severity_score': 'തീവ്രതാ സ്കോർ',
  'severity_high': 'ഉയർന്നത്',
  'severity_medium': 'ഇടത്തരം',
  'severity_low': 'കുറഞ്ഞത്',
  'environmental_status': 'പരിസ്ഥിതി നില',
  'confidence_metrics': 'വിശ്വാസ്യത അളവുകൾ',
  'ai_recommendation': 'AI ശുപാർശ',
  'soil_correction': 'മണ്ണ് തിരുത്തൽ',
  'model_precision': 'മോഡൽ കൃത്യത',
  'verified_ai': 'AgriPulse AI പരിശോധിച്ചു',
  'findings': 'കണ്ടെത്തലുകൾ',
  'confidence_score_cap': 'വിശ്വാസ്യത സ്കോർ',
  'qtl_acre': 'ക്വിന്റൽ/ഏക്കർ',
  'clear_history': 'ചരിത്രം മായ്‌ക്കുക',
  'clear_history_confirm': 'എല്ലാ ചരിത്രവും മായ്‌ക്കണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
  'delete_plot': 'പ്ലോട്ട് നീക്കം ചെയ്യുക',
  'delete_plot_confirm': 'ഈ പ്ലോട്ട് നീക്കം ചെയ്യണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
  'clear': 'മായ്‌ക്കുക',
  'cancel': 'റദ്ദാക്കുക',
  'market_insights': 'വിപണി ഉൾക്കാഴ്ചകൾ',
  'treatment_plan': 'ചികിത്സാ പദ്ധതി',
  'humidity': 'ആർദ്രത',
  'confidence_level': 'വിശ്വാസ്യത നില',
  'jan': 'ജനുവരി',
  'feb': 'ഫെബ്രുവരി',
  'mar': 'മാർച്ച്',
  'apr': 'ഏപ്രിൽ',
  'may': 'മേയ്',
  'jun': 'ജൂൺ',
  'jul': 'ജൂലൈ',
  'aug': 'ഓഗസ്റ്റ്',
  'sep': 'സെപ്റ്റംബർ',
  'oct': 'ഒക്ടോബർ',
  'nov': 'നവംബർ',
  'dec': 'ഡിസംബർ',
  'analysis_failed_connection': 'വിശകലനം പരാജയപ്പെട്ടു. കണക്ഷൻ പിശക്.',
  'refinement_failed': 'പരിഷ്ക്കരണം പരാജയപ്പെട്ടു',
  'audio_empty_error': 'സെർവറിൽ നിന്ന് ശൂന്യമായ ഓഡിയോ ലഭിച്ചു.',
  'audio_play_failed': 'ഉപദേശം കേൾപ്പിക്കാൻ പരാജയപ്പെട്ടു',
  'unknown_issue': 'അജ്ഞാതമായ പ്രശ്നം',
  'consult_expert': 'ഒരു വിദഗ്ദ്ധനെ സമീപിക്കുക.',
  'no_advice_available': 'ഉപദേശങ്ങളൊന്നും ലഭ്യമല്ല.',
  'diagnosis_prefix': 'രോഗനിർണ്ണയം',
  'recommendation_prefix': 'ശുപാർശ',
  'scan_in': 'സ്കാൻ:',
  'irrigation_stage': 'ജലസേചന ഘട്ടം',
  'weather_events': 'കാലാവസ്ഥാ സംഭവങ്ങൾ',
  'spread_pattern': 'വ്യാപന രീതി',
  'intervention_log': 'ഇടപെടൽ ലോഗ്',
  'establishment': 'സ്ഥാപനം',
  'sprouting': 'മുളയ്ക്കൽ',
  'leaf_dev': 'ഇല വികാസം',
  'bulb_init': 'കിഴങ്ങ് തുടക്കം',
  'bulb_dev': 'കിഴങ്ങ് വികാസം',
  'bone_dry': 'വരണ്ട',
  'moist': 'ഈർപ്പമുള്ള',
  'waterlogged': 'വെള്ളക്കെട്ടുള്ള',
  'frost': 'മഞ്ഞ്',
  'heavy_rain': 'ശക്തമായ മഴ',
  'drizzle': 'ചാറ്റൽ മഴ',
  'wind': 'കാറ്റ്',
  'too_hot': 'അമിത ചൂട്',
  'isolated': 'ഒറ്റപ്പെട്ട',
  'localized': 'പ്രാദേശികം',
  'field_wide': 'തോട്ടം ആകെ',
  'last_treatment': 'അവസാന ചികിത്സ',
  'dosage': 'അളവ്',
  'fert_organic': 'ജൈവം',
  'fert_npk': 'NPK',
  'fungicide': 'കുമിൾനാശിനി',
  'insecticide': 'കീടനാശിനി',
  'low': 'കുറഞ്ഞ',
  'medium': 'മിതമായ',
  'high': 'അதிகമായ',
  'workspace_context': 'ഫീൽഡ് സന്ദർഭം',
  'leaf_texture': 'ഇലയുടെ ഘടന',
  'texture_brittle': 'പൊട്ടിപ്പോകുന്ന',
  'texture_slimy': 'കൊഴുത്ത/മൃദുവാయ',
  'texture_rubbery': 'റബ്ബർ പോലെയുള്ള',
  'odor_presence': 'ഗന്ധത്തിന്റെ സാന്നിധ്യം',
  'odor_foul': 'ദുർഗന്ധം',
  'odor_none': 'ഗന്ധമില്ല',
  'speed_of_spread': 'പടരുന്ന വേഗത',
  'spread_overnight': 'ഒറ്റരാത്രികൊണ്ട് പ്രത്യക്ഷപ്പെട്ടു',
  'spread_slow': 'സാവധാനം പടരുന്നു',
  'role_user': 'നിങ്ങൾ',
  'role_ai': 'AgriPulse AI',
  'analysis_complete': 'വിശകലനം പൂർത്തിയായി',
  'default_ai_response': 'നിങ്ങളുടെ പ്രതികരണത്തെ അടിസ്ഥാനമാക്കിയുള്ള രോഗനിർണയം.',
  'treatment_adjustment_label': 'മാറ്റം',
  'sidebar_waiting_hint': 'വിശകലനത്തിനായി കാത്തിരിക്കുന്നു... അത് ദൃശ്യമാകുമ്പോൾ AI രോഗനിർണയം മെച്ചപ്പെടുത്താൻ ഈ വിഭാഗം ഉപയോഗിക്കുക.',
  'view_report': 'റിപ്പോർട്ട് കാണുക',
  'initial_request': 'പ്രാഥമിക അഭ്യർത്ഥന',
  'initial_diagnosis': 'പ്രാഥമിക രോഗനിർണയം',
  'refined_diagnosis': 'പരിഷ്കരിച്ച രോഗനിర్ണയം',
  'refinement_reasoning': 'പരിഷ്കരണ യുക്തി',
  'refinement_feedback': 'പരിഷ്കരണ പ്രതികരണം',
  'ai_findings': 'AI കണ്ടെത്തലുകൾ',
  'adjusted_treatment_plan': 'ക്രമീകരിച്ച ചികിത്സാ പദ്ധതി',
  'view_standard_treatment': 'സാധാരണ ചികിത്സ കാണുക',
  'view_adjusted_plan': 'ക്രമീകരിച്ച പ്ലാൻ കാണുക',
  'delete': 'നീക്കം ചെയ്യുക',
  'delete_record_confirm': 'ഈ റെക്കോർഡ് നീക്കം ചെയ്യണമെന്ന് നിങ്ങൾക്ക് ഉറപ്പാണോ?',
  'record_deleted': 'റെക്കോർഡ് നീക്കം ചെയ്തു',
  'prediction': 'പ്രവചനം',
  'forecast': 'മുൻകൂട്ടി കാണുക',
  'diagnosis_report': 'രോഗനിർണയ റിപ്പോർട്ട്',
  'date_label': 'തീയതി:',
  'disease_label': 'രോഗം:',
  'confidence_label': 'വിശ്വാസ്യത:',
  'diagnostic_findings_title': 'രോഗനിർണയ കണ്ടെത്തലുകൾ',
  'standard_treatment_plan': 'സാധാരണ ചികിത്സാ പദ്ധതി:',
  'treatment_adjustments': 'ചികിത്സാ ക്രമീകരണങ്ങൾ',
  'sharing_report': 'റിപ്പോർട്ട് പങ്കിടുന്നു...',
  'downloading_pdf': 'PDF ഡൗൺലോഡ് ചെയ്യുന്നു...',
  'download_pdf_button': 'PDF ഡൗൺലോഡ് ചെയ്യുക',
  'share_button': 'പങ്കിടുക',
  'severity': 'തീവ്രത',
  'temp': 'താപനില',
  'moisture': 'ഈർപ്പം',
  'analysis_metrics': 'അനാലിസിസ് മെട്രിക്സ്',
  'evidence': 'തെളിവ്',
  'analyzed_evidence': 'വിശകലനം ചെയ്ത തെളിവുകൾ',
  'completed': 'പൂർത്തിയായി',
  'no_feedback_provided': 'അഭിപ്രായം ഒന്നും നൽകിയിട്ടില്ല',
  'share': 'പങ്കിടുക',
  'verifying_securely': 'സുരക്ഷിതമായി പരിശോധിക്കുന്നു...',
  'offline_mode_warning': 'നിങ്ങൾ ഓഫ്‌ലൈനിലാണ്. കാഷെ ചെയ്ത ഡാറ്റ കാണിക്കുന്നു.',
  'yield_prediction_failed': 'വിളവ് പ്രവചനം പരാജയപ്പെട്ടു',
  'select_params_warning': 'പ്രവചനം നടത്തുന്നതിന് മുമ്പ് ദയവായി എല്ലാ ഫീൽഡ് പാരാമീറ്ററുകളും തിരഞ്ഞെടുക്കുക.',
  'confidence_suffix': 'CONF',
  // Single-page onboarding
  'welcome_setup_first_plot': 'സ്വാഗതം! നിങ്ങളുടെ ആദ്യ പ്ലോട്ട് സജ്ജീകരിക്കാം',
  'skip_demo': 'രജിസ്ട്രേഷൻ ഒഴിവാക്കുക (ഡെമോ)',
  'demo_plot_name': 'ഡെമോ പ്ലോട്ട്',
  'unlock_ai_insights': 'AI-പവർഡ് ഫാമിംഗ് ഇൻസൈറ്റുകൾ അൺലോക്ക് ചെയ്യാൻ നിങ്ങളുടെ ആദ്യ പ്ലോട്ട് സജ്ജീകരിക്കുക',
  'get_started': 'ആരംഭിക്കുക',
  // Plot deletion
  'delete_only_plot_warning': 'ഇത് നിങ്ങളുടെ ഏക പ്ലോട്ട് ആണ്. ഇത് ഇല്ലാതാക്കുന്നത് ആപ്പ് ഉപയോഗിക്കുന്നതിന് മുമ്പ് ഒരു പുതിയ പ്ലോട്ട് സജ്ജീകരിക്കേണ്ടതുണ്ട്.',
  'redirect_to_setup_hint': 'ഇല്ലാതാക്കിയതിനുശേഷം നിങ്ങളെ പ്ലോട്ട് സജ്ജീകരണത്തിലേക്ക് റീഡയറക്ട് ചെയ്യും.',
};
