import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'core/theme/app_theme.dart';
import 'core/router/app_router.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  // TODO: Run `flutterfire configure` to generate firebase_options.dart
  // For now, we wrap in try-catch to allow UI development without Firebase keys present
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("⚠️ Firebase initialization failed: $e");
    debugPrint("ℹ️  Running in UI-only mode. Provide firebase_options.dart to enable Auth/Firestore.");
  }

  runApp(
    const ProviderScope(
      child: AgriPulseApp(),
    ),
  );
}

class AgriPulseApp extends StatelessWidget {
  const AgriPulseApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'AgriPulse - Intelligent Farming',
      debugShowCheckedModeBanner: false,
      
      // Theme Configuration with specialized "Earth & Growth" palette
      theme: AppTheme.lightTheme,
      
      // Routing
      routerConfig: AppRouter.router,
    );
  }
}
