import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:firebase_core/firebase_core.dart';
import 'core/theme/app_theme.dart';
import 'core/router/app_router.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure
import 'features/crop_diagnosis/models/diagnosis_record.dart';
import 'features/yield_prediction/models/yield_record.dart';
import 'core/models/weather_cache.dart';
import 'core/services/local_vault.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  debugPrint("🚀 AgriPulse: Widgets initialized.");
  
  // Initialize Hive for local caching
  try {
    await Hive.initFlutter();
    debugPrint("✅ AgriPulse: Hive initialized.");
  } catch (e) {
    debugPrint("❌ AgriPulse: Hive failed: $e");
  }
  
  // Register Adapters (Type IDs: 0, 1, 2)
  Hive.registerAdapter(DiagnosisRecordAdapter());
  Hive.registerAdapter(YieldRecordAdapter());
  Hive.registerAdapter(WeatherCacheAdapter());
  
  // Initialize LocalVault Service
  try {
    await LocalVault().init();
    debugPrint("✅ AgriPulse: LocalVault initialized.");
  } catch (e) {
    debugPrint("❌ AgriPulse: LocalVault failed: $e");
  }
  
  // Initialize Firebase
  // TODO: Run `flutterfire configure` to generate firebase_options.dart
  // For now, we wrap in try-catch to allow UI development without Firebase keys present
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("⚠️ Firebase initialization failed: $e");
    debugPrint("ℹ️  Running in UI-only mode. Provide firebase_options.dart to enable Auth/Firestore.");
  }

  runApp(
    const ProviderScope(
      child: AgriPulseApp(),
    ),
  );
}

class AgriPulseApp extends ConsumerWidget {
  const AgriPulseApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    
    return MaterialApp.router(
      title: 'AgriPulse - Intelligent Farming',
      debugShowCheckedModeBanner: false,
      
      // Theme Configuration with specialized "Earth & Growth" palette
      theme: AppTheme.lightTheme,
      
      // Routing
      routerConfig: router,
    );
  }
}
